import numpy as np
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
from IPython.display import display
import random as rdm

drugs_master = {
    #    'drugname' : 'drugclass - drugindication'
    'abacavir' : 'antiretrovirals - HIV infection',
    'abatacept' : 'T-cell activation inhibitors - rheumatoid arthritis, psoriatic arthritis',
    'abemaciclib' : 'chemotherapy - protein kinase inhibitor - breast cancer',
    'abrocitinib' : 'DMARD - JAK1 inhibitor - severe atopic eczema',
    'acalabrutinib' : 'chemotherapy - protein kinase inhibitor - CLL',
    'acarbose' : 'intestinal glucosidase inhibitor - T2DM',
    'acebutolol' : 'beta blocker - hypertension, angina, arrhythmias',
    'aceclofenac' : 'NSAID - pain and inflammation in RA, OA and AS',
    'acenocoumarol' : 'vitamin K antagonist - prophylaxis of embolisation, VTE and TIA',
    'acetazolamide' : 'carbonic anhydrase inhibitor - glaucoma',
    'acetylcysteine' : 'antidote, mucolytic - paracetamol overdose, tear deficiency',
    'aciclovir' : 'antivirals - nucleoside analogues - HSV, VZV infection',
    'acipimox' : 'nicotinic acid derivatives - hyperlipidaemia',
    'acitretin' : 'retinoids - severe psoriasis',
    'acrivastine' : 'non-sedating antihistamine - allergic reactions',
    'adalimumab' : 'DMARD - TNF-a inhibitor - plaque psoriasis, RA, psoriatic arthritis, crohns disease, ulcerative colitis, uveitis',
    'adapalene' : 'retinoids - acne vulgaris',
    'adenosine' : 'antiarrhythmics - paroxysmal SVT, WpW syndrome',
    'adrenaline' : 'alpha and beta agonists - CpR, acute hypotension, anaphylaxis',
    'afatinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'aflibercept' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, ',
    'agratoban' : 'direct thrombin inhibitors - unstable angina/NSTEMI, STEMI pCI',
    'agomelatine' : 'melatonin receptor agonists, serotonin receptor antagonist - major depression',
    'alectinib' : 'chemotherapy - protein kinase inhibitor - ALK+ non-small cell lung cancer',
    'alemtuzumab' : 'anti-lymphocyte monoclonal antibodies - MS',
    'alfacalcidol' : 'vitamins and analogues - vitamin D deficiency',
    'alfentanil' : 'opioids - ventilation, pain in palliative care',
    'alirocumab' : 'lipid modigying drugs - hyperlipidaemia',
    'aliskiren' : 'renin inhibitors - hypertension',
    'alitretinoin' : 'retinoids - severe hand eczema',
    'allopurinol' : 'xanthine oxidase inhibitors - gout prophylaxis',
    'almotriptan' : 'triptans - acute migraine',
    'alogliptin' : 'DPP4 inhibitor - T2DM',
    'alpelisib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'alprazolam' : 'benzodiazepines - anxiety',
    'alprostadil' : 'prostaglandins and analogues - erectile dysfunction',
    'alteplase' : 'fibrinolytics (plasminogen activators) - acute MI, pE, acute ischaemic stroke',
    'ambrisentan' : 'endothelin receptor antagonists - pulmonary hypertension',
    'amifampridine' : 'cholinergic receptor stimulators - Lambert-Eaton myasthenic syndrome',
    'amikacin' : 'aminoglycosides - gram negative bacterial infections, prostatitis, pyelonephritis',
    'aminophylline' : 'xanthines - severe acute asthma, severe acute exacerbation of COPD',
    'amiodarones' : 'antiarrhythmics, class III - arrhytmmias, VF or pulseless VT in CpR',
    'amisulpride' : 'antipsychotics, second generation - schizophrenia',
    'amitriptyline' : 'tricyclic antidepressants - depression, neuropathic pain, abdominal pain, migraine prophylaxis',
    'amivantamab' : 'anti-EGFR monoclonal antibodies - non-small cell lung cancer with EGFR mutations',
    'amlodipine' : 'calcium channel blockers - angina, hypertension',
    'amorolfine' : 'antifungals - fungal nail infection',
    'amoxicillin' : 'penicillins - oral infections, UTI, community acquired pneumonia, COPD exacerbation, otis media, diverticulitis, H pylori eradication, endocarditis',
    'ampicillin' : 'penicillins - bronchitis, UTI, otis media, sinusitis, community acquired pneumonia, endocarditis',
    'amsacrine' : 'antineoplastics, other - acute leukaemia',
    'anakinra' : 'DMARD - interleukin inhibitors - rheumatoid arthritis, Stills disease',
    'anastrozole' : 'aromatase inhibitors - adjuvant in oestrogen-receptor positive breast cancer',
    'anidulafungin' : 'echinocandin antifungals - invasive candidiasis',
    'apalutamide' : 'androgen receptor inhibitors - prostate cancer',
    'apixaban' : 'direct factor Xa inhibitor - VTE/pE prophylaxis',
    'apraclonidine' : 'alpha 2 receptor agonist - glaucoma',
    'apremilast' : 'PDE4 inhibitor - psoriatic arthritis, plaque psoriasis',
    'aprepitant' : 'neurokinin receptor antagonists - antiemetic - chemotherapy associated nausea and vomiting',
    'aripiprazole' : 'antipsychotics, second generation - schizophrenia',
    'asciminib' : 'chemotherapy - protein kinase inhibitor - CML (philadelphia chromosome positive)',
    'asenapine' : 'antipsychotics, second generation - mania in bipolar disorder',
    'asparaginase' : 'antineoplastics, other - ALL',
    'aspirin' : 'NSAID, antiplatelet drugs - pain, secondary prevention in CVD/DVT/pE, TIA, STEMI, NSTEMI, AF',
    'ataluren' : 'dystrophin synthesis restorer - DMD',
    'atazanavir' : 'antiretroviral - HIV infection',
    'atenolol' : 'beta blocker - hypertension, angina, arrhythmias, migraine prophylaxis',
    'atezolizumab' : 'anti-pD-L1 monoclonal antibody - urothelial carcinoma, lung cancer, breast cancer, hepatocellular carcinoma',
    'atomoxetine' : 'sympathomimetics - ADHD',
    'atorvastatin' : 'HMG CoA reductase inhibitors - hyperlipidaemia, secondary prevention of CVD',
    'atovaquone' : 'antiprotozoals - pneumocystis pneumonia',
    'atracurium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'atropine' : 'antimuscarinics - organophosphate poisoning, bradycardia',
    'avacopan' : 'Immunomodulating drugs - granulomatosis with polyangiitis, microscopic polyangiitis',
    'avanafil' : 'PDE5 inhibitors - erectile dysfunction',
    'avapritinib' : 'chemotherapy - protein kinase inhibitor - gastro-intestinal stromal tumours',
    'avelumab' : 'anti-pD-L1 monoclonal antibody - renal. cell carcinoma, merkel cell carcinoma, urothelial carcinoma',
    'axitinib' : 'chemotherapy - protein kinase inhibitor - renal. cell carcinoma',
    'azacitidine' : 'chemotherapy - antimetabolites - myelodysplastic syndrome, CML, AML',
    'azathioprine' : 'DMARD - antimetabolite - crohns disease, RA, SLE, polymyositis, transplant rejection suppression, myasthenia gravis',
    'azithromycin' : 'macrolide antibiotics - GAS prevention, URTI, otis media, skin infections, chlamydia, conorrhoea, community acquired pneumonia',
    'aztreonam' : 'betalactam antibiotic - gram negative bacterial infections, prostatitis, pyelonephritis',
    'baclofen' : 'muscle relaxants - muscle spasm, hiccup in palliative care',
    'baricitinib' : 'DMARD - JAK1 inhibitor - RA, atopic eczema',
    'basiliximab' : 'anti-lymphocyte monoclonal antibodies - transplant rejection prophylaxis',
    'bedaquiline' : 'antimycobacterials - multi-drug resistant pulmonary TB',
    'belatacept' : 'T-cell activation innhibitors - transplant rejection prophylaxis',
    'belimumab' : 'anti-lymphocyte monoclonal antibodies - SLE',
    'benperidol' : 'antipsychotics, first generation - deviant antisocial sexual behaviour',
    'benralizumab' : 'anti-IL5 monoclonal antibodies - severe eosinophilic asthma',
    'berotralstat' : 'plasma kallikrein inhibitor - hereditary angioedema',
    'betaine' : '? - homocystinuria',
    'betamethasone' : 'corticosteroids - inflammation, immunosuppression',
    'betaxolol' : 'beta blocker - ocular hypertension, chronic glaucoma',
    'bevacizumab' : 'VEGF inhibitors - colorectal, breast, renal cell, lung, ovarian, cervical, hepatocellular cancers',
    'bexarotene' : 'chemotherapy - retinoids - cutaneous T-cell lymphoma',
    'bezafibrate' : 'fibrates - hyperlipidaemia',
    'bezlotoxumab' : 'antitoxins - C diff prophylaxis',
    'bicalutamide' : 'androgen receptor inhibitors - prostate cancer',
    'bilastine' : 'non-sedating antihistamine - allergic reactions',
    'bimatoprost' : 'prostamides - ocular hypertension, chronic glaucoma',
    'bimekizumab' : 'DMARD - interleukin inhibitors - plaque psoriasis',
    'binimetinib' : 'chemotherapy - protein kinase inhibitor - BRAF +ve metastatic melanoma',
    'bisacodyl' : 'stimulant laxatives - Constipation',
    'bivalirudin' : 'direct thrombin inhibitors - unstable angina/NSTEMI, STEMI pCI',
    'bleomycin' : 'chemotherapy - cytotixc antibiotics - SCC, metastatic germ cell cancer, non-hodgkins lymphoma',
    'blinatumomab' : 'anti-lymphocyte monoclonal antibodies - ALL (philidelphia chromosome -ve)',
    'bortezomib' : 'chemotherapy - proteasome inhibitors - multiple myeloma, mantle cell lymphoma',
    'bosentan' : 'endothelin receptor antagonists - pulmonary hypertension',
    'bosutinib' : 'chemotherapy - protein kinase inhibitor - CML (philadelphia chromosome positive)',
    'brigatinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'brinzolamide' : 'carbonic anhydrase inhibitor - ocular hypertension, chronic glaucoma',
    'brivaracetam' : 'antiepileptics - focal seizures',
    'brodalumab' : 'DMARD - interleukin inhibitors - plaque psoriasis',
    'brolucizumab' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, ',
    'bromfenac' : 'NSAID - post-op inflamation',
    'bromocriptine' : 'dopamine receptor agonists - galactorrhoea, acromegaly, prolactinoma, parkinsons disease',
    'budesonide' : 'corticosteroids - asthmma, allergic rhinitis, nasal polyps',
    'bumetanide' : 'loop diuretic - oedema',
    'buprenorphine' : 'opioid receptor antagonists - pain, opioid dependence',
    'buserelin' : 'gonadotrophin releasing hormones - endometriosis, IVF, prostate cancer',
    'busulfan' : 'chemotherapy - alkylating agents - CML',
    'cabazitaxel' : 'chemotherapy - taxanes - prostate cancer',
    'cabergoline' : 'dopamine receptor agonists - galactorrhoea, parkinsons disease',
    'cabotegravir' : 'antiretroviral - HIV infection',
    'cabozantinib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, medullary thyroid cancer, hepatocellular carcinoma',
    'calcipotriol' : 'vitamins and analogues - plaque psoriasis',
    'calcitriol' : 'vitamins and analogues - plaque psoriasis, renal osteodystrophy, osteoporosis',
    'canagliflozin' : 'SGLT2 inhibitors - T2DM',
    'canakinumab' : 'DMARD - interleukin inhibitors - gouty arthritis, familial mediterranean fever, stills disease, cryopyrin period syndrome',
    'candesartan' : 'ARB - hypertension, heart failure',
    'cangrelor' : 'antiplatelet drugs - thrombosis prophylaxis in pCI',
    'cannabidiol' : 'antiepileptics - seizures associated with Lennox-gastaut syndrome, Dravet syndrome, tuberous sclerosis complex',
    'capecitabine' : 'chemotherapy - antimetabolites - colorectal cancer, gastric cancer, breast cancer',
    'caplacizumab' : 'antiplatelet monoclonal antibody - acquired thrombotic thrombocytopenic purpura',
    'capreomycin' : 'antimycobacterials - TB',
    'capsaicin' : 'plant alkaloids - neuropathic pain',
    'captopril' : 'ACEi - hypertension, heart failure, diabetic nephropathy',
    'carbamazepine' : 'antiepileptics - tonic-clonic seizures, trigeminal neuralgia, bipolar disorder, diabetic neuropathy',
    'carbimazole' : '?? - hyperthyroidism',
    'carbocisteine' : 'mucolytics - excess sputum',
    'carbomers' : 'ocular lubricants - dry eyes',
    'carboplatin' : 'chemotherapy - platinum compounds - ovarian cancer, small cell lung cancer, seminoma testicular germ cell tumours',
    'carboprost' : 'prostaglandins and analogues - postpartum haemorrhage',
    'carfilzomib' : 'chemotherapy - proteasome inhibitors - multiple myeloma',
    'cariprazine' : 'antipsychotics, second generation - schizophrenia',
    'carmustine' : 'chemotherapy - alkylating agents - brain tumours, multiple myeloma, non-hodgkins lymphoma, hodgkins disease, glioblastoma',
    'carvedilol' : 'alpha and beta blockers - hypertension, angina, heart failure',
    'caspofungin' : 'antifungals - invasive candidiasis, invasive asperfillosis',
    'cefaclor' : 'cephalosporin antibiotics - bacterial infections, pneumonia, LUTI',
    'cefadroxil' : 'cephalosporin antibiotics - bacterial infections, skin and soft tissue infection, LUTI',
    'cefalexin' : 'cephalosporin antibiotics - bacterial infections, hospital acquired pneumonia, diverticulitis, UTI, pyelonephritis',
    'cefazolin' : 'cephalosporin antibiotics - bacterial infections, skin and soft tissue infection, surgical prophylaxis, joint and bone infection',
    'cefepime' : 'cephalosporin antibiotics - bacterial infections, LUTI',
    'cefixime' : 'cephalosporin antibiotics - bacterial infections, gonnorrhoea',
    'cefotaxime' : 'cephalosporin antibiotics - bacterial infections, gonnorrhoea, meningitis',
    'cefoxitin' : 'cephalosporin antibiotics - bacterial infections, UTI',
    'cefradine' : 'cephalosporin antibiotics - bacterial infections, surgical prophylaxis',
    'ceftazidime' : 'cephalosporin antibiotics - bacterial infections, hospital acquired pneumonia, meningitis, febrile neutropenia, septicaemia',
    'ceftobiprole' : 'cephalosporin antibiotics - pneumonia ',
    'ceftriaxone' : 'cephalosporin antibiotics - bacterial infections, pneumonia, UTI, COPD exacerbation, skin and soft tissue infections, prophylaxis from bites, meningitis, endocarditis, surgical prophylaxis, fonorrhoea',
    'cefuroxime' : 'cephalosporin antibiotics - bacterial infections, pneumonia, cellulitis, bite prophylaxis, divertiulitis, surgical prophylaxis, UTI',
    'celecoxib' : 'NSAID - pain and inflammation in RA, OA and AS',
    'cemiplimab' : 'anti-pD1 monoclonal antibody - SCC',
    'cenobamate' : 'antiepileptics - focal seizures',
    'ceritinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'cetrorelix' : 'anti-gonadotrophin releasing hormones - infertility',
    'cetirizine' : 'non-sedating antihistamine - allergic reactions',
    'cetuximab' : 'chemotherapy - monoclonal antibodies - colorectal cancer, SCC',
    'chlorambucil' : 'chemotherapy - alkylating agents - lymphoma, CLL, CML',
    'chlorhexidine' : 'antiseptics - oral candidiasis, gingivitis, stomatitis, aphthous ulcers, ',
    'chlormethine' : 'chemotherapy - alkylating agents - mycosis fungoides',
    'chloroquine' : 'antimalarials - RA, SLE, malaria prophylaxis and treatmment',
    'chlortalidone' : 'thiazide like diuretics - ascites, hypertension, heart failure, diabetes insipidus',
    'ciclesonide' : 'corticosteroids - asthma',
    'ciclosporin' : 'calcineurin inhibitors - nephrotic syndrome, transplant rejection, UC , psoriasis, dermatitis, RA',
    'cilostazol' : 'antiplatelet drugs - intermittent claudication',
    'cimetidine' : 'H2 receptor antagonists - gastroduodenal ulceration, reflux oesophagitis, gastric acid reduction',
    'cinacalcet' : 'Bone resorption inhibitors - secondary hyperparathyroidism, hypercalcaemia in parathyroid carcinoma, primary hyperparathyroidism',
    'cinnarizine' : 'sedating antihistamines - vestibular disorders, motion sickness, ',
    'ciprofibrate' : 'fibrates - hyperlipidaemia',
    'ciprofloxacin' : 'quinolone antibiotics - UTI, meningitis prophylaxis, anthrax, RTI, diverticulitis, eye infections',
    'cisatracurium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'cisplatin' : 'chemotherapy - platinum compounds - testicular, lung, cervical, bladder, head and neck, and ovarian cancer',
    'citalopram' : 'SSRIs - depression, panic disorder',
    'cladribine' : 'chemotherapy - antimetabolites - leukaemia, relapsing remitting MS',
    'clarithromycin' : 'macrolide antibiotics - skin and soft tissue infections, pneumonia, RTI, COPD exacerbation, H pylori, sinusitis, otis media',
    'clemastine' : 'sedating antihistamines - allergic reactions',
    'clindamycin' : 'lincosamides - staphylococcal infections, MRSA, skin and soft tissue infections',
    'clobazam' : 'benzodiazepines - anxiety',
    'clofazimine' : 'antimycobacterials, antimetabolites - leprosy',
    'clomethiazole' : 'non-benzodiazepine sedatives and hypnotics - insomnia, agitation, alcohol withdrawal',
    'clonazepam' : 'benzodiazepines - anxiety, epilepsy',
    'clopidogrel' : 'antiplatelet drugs - atherothrombosis prvention, TIA, MI, AF',
    'clotrimazole' : 'antifungals - fungal skin infections, candidiasis',
    'clozapine' : 'antipsychotics, second generation - schizophrenia, psychosis in parkinsons disease',
    'cobimetinib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma',
    'colchicine' : 'plant alkaloids - acute gout, familial mediterranean fever prophylaxis',
    'colecalciferol' : 'vitamins and analogues - vitamin D deficiency',
    'colestyramine' : 'bile acid sequestrants - hyperlipidaemia, secondary prevention of CVD, diarrhoea',
    'codeine' : 'opioids - pain',
    'crisantaspase' : 'antineoplastics, other - ALL',
    'crizanlizumab' : 'DMARD - monoclonal antibody - sickle cell disease',
    'crizotinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'crotamiton' : 'antipruritics - pruritus',
    'cyanocobalamin' : 'vitamins and analogues - B12 deficiency, pernicious anaemia',
    'cyclizine' : 'antihistamines - nausea and vomiting in paliative care, motion sickness, vertigo',
    'cycloserine' : 'antimycobacterials - TB',
    'cytarabine' : 'chemotherapy - antimetabolites - ALL',
    'dabigatran' : 'direct thrombin inhibitors - unstable angina/NSTEMI, STEMI pCI',
    'dabrafenib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma (BRAF +ve)',
    'dacarbazine' : 'chemotherapy - alkylating agents - metastatic melanoma, soft tissue sarcomas, hodgkins disease',
    'dacomitinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'dalteparin' : 'heparins - DVT/pE treatment',
    'dalbavancin ' : 'glycopeptide antibiotics - skin and soft tissue infections',
    'dapagliflozin' : 'SGLT2 inhibitors - T2DM, heart falure, CKD',
    'dapoxetine' : 'SSRIs - premature ejaculation',
    'dapsone' : 'antimycobacterials - leprosy, dermatitis herperiformis, pJp',
    'dantrolene' : 'antispasmodics - msucle cramps in MND, severe spasticity, malignant hyperthermia',
    'dabigatran' : 'direct thrombin inhibitors - VTE prophylaxis, DVT/pE treatment and prophylaxis, embolic prophylaxis',
    'darbopoetin' : 'epoetins - anaemia in chronic renal failure',
    'daptomycin' : 'lipopeptide antibiotic - complicated gram positive infections',
    'daratumumab' : 'chemotherapy - monoclonal antibodies - multiple myeloma, light chain amyloidosis',
    'darifenacin' : 'antimuscarinics - urinary frequency, urgency and incontinence',
    'darolutamide' : 'androgen receptor inhibitors - prostate cancer',
    'darunavir' : 'antiretroviral - HIV infection',
    'dasatinib' : 'chemotherapy - protein kinase inhibitor - CML, ALL',
    'daunorubicin' : 'chemotherapy - anthracyclines - AML, ALL, Kaposis sarcoma',
    'deferasirox' : 'iron cheletors - chronic iron overload',
    'deferiprone' : 'iron cheletors - thalassaemia iron overload',
    'deflazacort' : 'corticosteroids - suppression of inflammatory and allergic disorders',
    'degarelix' : 'anti-gonadotrophin releasing hormones - prostate cancer',
    'delafloxacin' : 'quinolone antibiotics - skin and soft tissue infections',
    'delamanid' : 'antimycobacterials - TB',
    'denosumab' : 'DMARD - monoclonal antibody - osteoporosis',
    'desflurane' : 'volatile liquid anaesthetics - anaesthesia',
    'desloratadine' : 'non-sedating antihistamine - allergic reactions',
    'desmopressin' : 'ADH analogues - diabetes insipidus, nocturnal enuresis, polyuria and polydipsia, haemophilia, von-Willebrands disease',
    'desogestrel' : 'progestogens - contraception',
    'dexamethasone' : 'corticosteroids - suppression of inflammatory and allergic disorders, inflammation, macular oedema, croup, congenital adrenal hyperplasia, anorexia in paliative care, pain in paliative care, cerebral oedema, preterm labour',
    'dexketoprofen' : 'NSAID - pain',
    'diamorphine' : 'opioids - pain, acute pulmonary oedema, MI',
    'diazepam' : 'benzodiazepines - muscle spasm, tetanus, anxiety, insomnia, acute alcohol withdrawal, sedation, status epilepticus, dyspnoea in paliative care',
    'diazoxide' : 'glycogenolytic hormones - chronic intractable hypoglycaemia',
    'diclofenac' : 'NSAID - pain following dental treatment',
    'dienogest' : 'progestogens - endometriosis',
    'difelikefalin' : 'antipruritics - pruritus',
    'digoxin' : 'cardiac glycosides - atrial fibrillation or flutter, heart failure',
    'diltiazem' : 'calcium channel blockers - angina, hypertension, chronic anal fissure',
    'dihydrocodeine' : 'opioids - pain',
    'dimeticone' : 'parasiticides - head lice',
    'dinoprostone' : 'prostaglandins and analogues - induction of labour',
    'dipyridamole' : 'antiplatelet drugs - prevention of stroke, TIA, thromboembolism',
    'disopyramide' : 'antiarrhythmic agents - arrhythmias, maintenance of sinus rhythm',
    'disulfiram' : '?? - alcohol dependence',
    'dithranol' : 'antracen derivatives - chronic psoriasis',
    'docusate' : 'stimulant laxatives - constipation',
    'dobutamine' : 'sympathomimetics - inotropic support in infarction, shock, cardiomyopathies, and cardiac stress testing',
    'docetaxel' : 'chemotherapy - taxanes - breast cancer, non-small cell lung cancer, prostate cancer, gastric adenocarcinoma',
    'docusate' : 'softening laxatives - chronic constipation',
    'dolutegravir' : 'antiretroviral - HIV infection',
    'domperidone' : 'dopamine receptor antagonists - nausea and vomiting in paliative care',
    'donepezil' : 'acetylcholinesterase inhibitor - Alzheimers disease',
    'dopamine' : 'sympathomimetics - cardgiogenic shock',
    'doravirine' : 'antiretroviral - HIV infection',
    'dorzolamide' : 'carbonic anhydrase inhibitor - ocular hypertension, chronic glaucoma',
    'dostarlimab' : 'anti-pD1 monoclonal antibody - endometrial cancer',
    'doxazosin' : 'alpha-adrenoreceptor blockers - hypertension, BPH',
    'doxepin' : 'antipruritics, tricyclic antidepressants - pruritus, sedation in depression',
    'doxycycline' : 'tetracyclines - chlamydia, rickettsia, mycoplasma, other infections',
    'dronedarone' : 'antiarrhythmics, class III - maintenance of sinus rhythm',
    'droperidol' : 'antipsychotics, first generation - prevention of post operative nausea and vomiting',
    'dulaglutide' : 'GLp1 receptor agonist - T2DM',
    'duloxetine' : 'SNRI - depression, generalised anxiety disorder, diabetic neuropathy, urinary incontinence',
    'dupilumab' : 'DMARD - interleukin inhibitors - atopic eczema, severe asthma',
    'durvalumab' : 'anti-pD-L1 monoclonal antibody - non-small cell lung cancer',
    'dutasteride' : '5alpha reductase inhibitors - BPH',
    'eculizumab' : 'DMARD - monoclonal antibody - paroxysmal nocturnal haemoglobinuria, myasthenia gravis',
    'edoxaban' : 'direct factor Xa inhibitor - DVT/pE treatment and prophylaxis, embolism prophylaxis in AF',
    'efavirenz' : 'antiretroviral - HIV infection',
    'eflornithine' : 'antiprotozoals - facial hirsutism',
    'eletriptan' : 'triptans - migraine',
    'eliglustat' : 'glucosylceramide synthase inhibitors - gauchers disease',
    'elotuzumab' : 'anti-lymphocyte monoclonal antibodies - multiple myeloma',
    'eltrombopag' : 'thrombopoietin receptor agonist - chronic immune thrombocytopenic purpura',
    'elvitegravir' : 'antiretroviral - HIV infection',
    'emicizumab' : 'DMARD - monoclonal antibody - prophylaxis of haemorrhage in haemophilia A ',
    'empagliflozin' : 'SGLT2 inhibitors - T2DM, heart falure',
    'emtricitabine' : 'antiretroviral - HIV infection',
    'enalapril' : 'ACEi - hypertension, heart failure',
    'encorafenib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma (BRAF +ve)',
    'enfuvirtide' : 'antiretroviral - HIV infection',
    'enoximone' : 'PDE3 inhibitor - CHF with reduced CO',
    'entacapone' : 'catechol-o-methyltransferase inhibitors - parkinsons disease',
    'entecavir' : 'antivirals - nucleoside analogues - chronic hepatitis B',
    'enzalutamide' : 'androgen receptor inhibitors - prostate cancer',
    'eplerenone' : 'mineralocorticoid receptor antagonists - heart failure with reduced ejection fraction',
    'epoetin' : 'epoetins - anaemia in chronic renal failure',
    'epoprostenol' : 'prostaglandins and analogues - primary pulmonary hypertension, inhibition of platelet aggregation during dialysis',
    'eprosartan' : 'ARB - hypertension',
    'eptinezumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'eravacycline' : 'tetracyclines - complicated intra-abdominnal infections',
    'erdosteine' : 'mucolytics - bronchitis exacerbation',
    'erenumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'ergocalciferol' : 'vitamins and analogues - vitamin D deficiency, hypocalcaemia of hypoparathyroidism',
    'eribulin' : 'antineoplastics, other - metastatic breast cancer',
    'erlotinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer, metastatic pancreatic cancer',
    'ertapenem' : 'carbapenem antibiotics - abdominal infections, gynaecological infections, community acquired pneumonia, diabetic foot infections',
    'ertugliflozin' : 'SGLT2 inhibitors - T2DM',
    'erythromycin' : 'macrolide antibiotics - susceptible infections (e.g. legionella, campylobacter, skin) in penicillin hypersensitivity, impetigo, cellulitis, community acquired pneumonia, early syphilis, chlamydia, prostatisis, pertussis, acne, rosacea',
    'escitalopram' : 'SSRIs - depression, anxiety disorders, panic disorder, OCD',
    'esketamine' : 'NMDA receptor blocker - anaesthesia, emergency analgesia, major depressive disorder',
    'esomeprazole' : 'PPI - pUD, prophylaxis of NSAID associated ulcers, GORD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'estradiol' : 'oestrogens - vaginal atrophy in post-menopausal women, prophylaxis of recurrent UTI in post-menopausal women',
    'estriol' : 'oestrogens - vaginal atrophy in post-menopausal women, prophylaxis of recurrent UTI in post-menopausal women',
    'etanercept' : 'DMARD - TNF-a inhibitor - RA, psoriatic arthritis, AS, plaque psoriasis',
    'etelcalcetide' : 'Bone resorption inhibitors - secondary hyperparathyroidism',
    'ethosuximide' : 'antiepileptics - absence seizures, myoclonic seizures',
    'etodolac' : 'NSAID - pain in RA and OA',
    'etomidate' : 'IV anaesthetics - induction of anaesthesia',
    'etonogestrel' : 'progestogens - contraception',
    'etoposide' : 'chemotherapy - cytotoxic drugs - small cell carcinoma of bronchus, lymphomas, testicular cancer',
    'etoricoxib' : 'NSAID - pain and inflammation in RA, OA and AS, acute gout',
    'etravirine' : 'antiretroviral - HIV infection',
    'everolimus' : 'chemotherapy - protein kinase inhibitor - neuroendocrine tumours (pancreatic or gastro-intestinal origin)',
    'evolocumab' : 'lipid modifying drugs - hyperlipidaemia, homozygous familial hypercholesterolaemia',
    'exemestane' : 'aromatase inhibitors - adjuvant in oestrogen-receptor positive breast cancer',
    'exenatide' : 'GLp1 receptor agonist - T2DM',
    'ezetimibe' : 'cholesterol abbsorption inhibitors - adjunct in hyperlipidaemia',
    'famciclovir' : 'antivirals - nucleoside analogues - HSV, HZV infection',
    'famotidine' : 'H2 receptor antagonists - gastroduodenal ulceration, reflux oesophagitis',
    'fampridine' : 'cholinergic receptor stimulators - MS',
    'faricimab' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, ',
    'febuxostat' : 'xanthine oxidase inhibitors - chronic hyperuricaemia in gout, acute hyperuricaemia in haematologic malignancies',
    'fedratinib' : 'chemotherapy - protein kinase inhibitor - splenomegaly',
    'felbinac' : 'NSAID - pain in knee or hand osteoarthritis',
    'felodipine' : 'calcium channel blockers - angina, hypertension',
    'fenfluramine' : 'antiepileptics - seizures in Dravet syndrome',
    'fenofibrate' : 'fibrates - adjunct in hyperlipidaemia',
    'fentanyl' : 'opioids - severe pain, analgesia and anaesthesia during operation',
    'fidaxomicin' : 'macrocyclic antibiotic - C diff infection',
    'filgotinib' : 'DMARD - JAK1 inhibitor - RA, ulcerative colitis',
    'filgrastim' : 'granulocute colony stimulating factors - neutropenia',
    'finasteride' : '5alpha reductase inhibitors - BPH, androgenic alopecia',
    'finerenone' : 'mineralocorticoid receptor antagonists - CKD',
    'fingolimod' : 'sphingosine-1-phosphate receptor modulator - MS',
    'flecainide' : 'antiarrhythmics, class Ic - supraventricular arrhythmias, ventricular arrhythmias',
    'flucloxacillin' : 'penicillin antibiotics - betalacatmase producing staph infections, impetigo, cellulitis, diabetic foot infection, endocarditis',
    'fluconazole' : 'antifungals - candidiasis, balanitis, tinea infection, invasive candidal infection, prevention of fungal infections in immunocompromised patients',
    'flumazenil' : 'antidotes - reversal of sedative effects of benzodiazepines',
    'fluocinonide' : 'corticosteroids - severe eczema, psoriasis',
    'fluorouracil' : 'chemotherapy - antimetabolites - skin cancer, GI tract tumours, breast cancers, colorectal cancer',
    'fluoxetine' : 'SSRIs - major depression, bulimia nervosa, OCD disorder',
    'flupentixol' : 'antipsychotics, first generation - schizophrenia, depressive illness',
    'flurazepam' : 'benzodiazepines - insomnia',
    'flurbiprofen' : 'NSAID - pain, inhibition of intra-operative miosis',
    'flutamide' : 'androgen receptor inhibitors - prostate cancer',
    'fluticasone' : 'corticosteroids - asthma, allergic rhinitis, nasal polyps, psoriasis, severe inflammatory skin disorders',
    'fluvastatin' : 'HMG-CoA reductase inhibitor - hyperlipidaemia',
    'follitropin' : 'gonadotrophins - infertility',
    'formaldehyde' : 'aldehydes and derivatives - warts',
    'formoterol' : 'long acting beta agonists - COPD, asthma',
    'fosfomycin' : 'phosphonic acid antibiotic - UTI, osteomyelitis, meningitis',
    'fostemsavir' : 'antiretroviral - HIV infection',
    'fremanezumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'frovatriptan' : 'triptans - migraine',
    'fulvestrant' : 'anti-oestrogens - oestrogen receptor positive breast cancer',
    'furosemide' : 'loop diuretic - oedema, hypertension',
    'gabapentin' : 'antiepileptics - focal seizures, neuropathic pain, MS',
    'galantamine' : 'acetylcholinesterase inhibitor - Alzheimers disease',
    'galcanezumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'ganciclovir' : 'antivirals - nucleoside analogues - CMV infection, acure herpetic keratits',
    'ganirelix' : 'anti-gonadotrophin releasing hormones - infertility',
    'gefitinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'gemcitabine' : 'chemotherapy - antimetabolites - non-small cell lung cancer, pancreatic cancer, bladder cancer, ovarian cancer, breast cancer',
    'gemeprost' : 'prostaglandins and analogues - termination of pregnancy',
    'gemfibrozil' : 'fibrates - hyperlipidaemia',
    'gentamicin' : 'aminoglycoside antibiotics - gram positive or HACEK endocarditis, eye infections, diabetic foot infections, diverticulitis, meningitis, pneumonia, prostatitis, CNS infections, pyelonephritis',
    'gilteritinib' : 'chemotherapy - protein kinase inhibitor - AML',
    'givosiran' : 'interfering RNA - acute hepatic porphyria',
    'glasdegib' : 'antineoplastics, other - AML',
    'gliclazide' : 'sulfonylureas - T2DM',
    'glimepiride' : 'sulfonylureas - T2DM',
    'glipizide' : 'sulfonylureas - T2DM',
    'glucagon' : 'glycogenolytic hormones - diabetic hypoglycaemia, beta blocker overdose',
    'glucosamine' : 'natural substance - osteoarthritis of the knee',
    'glucose' : 'natural substance - hypoglycaemia, DKA',
    'glutaraldehyde' : 'aldehydes and derivatives - warts',
    'glycerol' : 'stimulant laxatives - constipation',
    'golimumab' : 'DMARD - TNF-a inhibitor - RA, psoriatic arthritis, AS, ulcerative colitis',
    'gonadorelin' : 'gonadotrophin releasing hormones - assessment of pituitary function',
    'goserelin' : 'gonadotrophin releasing hormones - prostate cancer',
    'granisetron' : 'serotonin receptor antagonists - nausea and vomiting',
    'griseofulvin' : 'antifungals - tinea pedis, dermatophyte infection',
    'guanfacine' : 'alpha-adrenoreceptor agonists - ADHD',
    'guselkumab' : 'DMARD - interleukin inhibitors - plaque psoriasis, psoriatic arthritis',
    'haloperidol' : 'antipsychotics, first generation - post-op nausea and vomiting, nausea and vomiting and restlessness in palliative care, schizophrenia, acute delirium, mania, agitation, severe tic disorders, chorea',
    'heparin' : 'heparins - pE/DVT, thromboprophylaxis, haemodialysis, unstable angina, acute peripheral arterial occlusion',
    'hydrocortisone' : 'corticosteroids - thyrotoxic crisis, adrenocortical insufficiency, anaphylaxis, corticosteroid replacement, Addisons disease, adrenal crisis, angioedema, severe IBD, acute asthma, inflammatory skin disorders',
    'hypromellose' : 'ocular lubricants - dry eyes',
    'ibrutinib' : 'chemotherapy - protein kinase inhibitor - mantle cell lymphoma, CLL, waldenstroms macroglobulinaemia',
    'ibuprofen' : 'NSAID - pain, migraine, inflammation, pyrexia',
    'ichthammol' : 'anti-infectives - chronic lichenified eczema',
    'idarucizumab' : 'antidotes - dabigatran reversal',
    'idebenone' : 'nootropics - lebers hereditary optic neuropathy',
    'idelalisib' : 'chemotherapy - protein kinase inhibitor - CLL, follicular lymphomma',
    'idursulfase' : 'enzymes - mucopolysaccharidosis',
    'ifosfamide' : 'chemotherapy - alkylating agents - malignant disease',
    'iloprost' : 'prostaglandins and analogues - pulmonary hypertension, raynauds disease, lower limb ischaemia',
    'imatinib' : 'chemotherapy - protein kinase inhibitor - CML, ALL, gastro-intestinal stromal tumours, myelodysplasia',
    'imiglucerase' : 'enzymes - gauchers disease',
    'imiquimod' : 'topical preparations - warts, actinic keratosis',
    'inclisiran' : 'lipid modifying drugs - hyperlipidaemia, homozygous familial hypercholesterolaemia',
    'indacaterol' : 'long acting beta agonists - COPD',
    'indapamide' : 'thiazide like diuretics - hypertension',
    'indometacin' : 'NSAID - pain and inflammation in RA, OA and AS, dysmenorrhoea, acute gout',
    'indoramin' : 'alpha-adrenoreceptor blockers - hypertension, BPH',
    'infliximab' : 'DMARD - TNF-a inhibitor - RA, psoriatic arthritis, AS, plaque psoriasis, crohns disease, ulcerative colitis',
    'insulin' : 'hormones and analogues - diabetes mellitus',
    'ipilimumab' : 'chemotherapy - monoclonal antibodies - melanoma, renal cell carcinoma, non-small cell lung cancer, mesothelioma, colorectal cancer',
    'ipratropium' : 'antimuscarinics - bronchospasm, acute asthma',
    'irbesartan' : 'ARB - hypertension, renal disease',
    'iron' : 'vitamins and analogues - iron deficient anaemia',
    'isatuximab' : 'chemotherapy - monoclonal antibodies - multiple myeloma',
    'isavuconazole' : 'antifungals - invasive aspergillosis',
    'isocarboxazid' : 'MAO inhibitors - depression',
    'isoflurane' : 'volatile liquid anaesthetics - anaesthesia',
    'isoniazid' : 'antimycobacterials - TB',
    'isotretinoin' : 'retinoids - acne vulgaris',
    'itraconazole' : 'antifungals - candidiasis, pityriasis versicolor, tinea infections, aspergillosis, crytococcosis',
    'ivabradine' : 'negative inotropes - angina, heart failure',
    'ivacaftor' : 'mucolytics - cystic fibrosis',
    'ivermectin' : 'antihelmintics - rosacea, scabes, onchocerciasis',
    'ixazomib' : 'chemotherapy - proteasome inhibitors - multiple myeloma',
    'ixekizumab' : 'DMARD - interleukin inhibitors - plaque psoriasis, psoriatic arthritis, spondyloarthritis',
    'kaolin' : 'antipropulsives - acute diarrhoea',
    'ketamine' : 'NMDA receptor blocker - anaesthesia, pain in palliative care, emergency analgesia',
    'ketoconazole' : 'antifungals - fungal skin infections, seborrhoeic dermatitis, pityriasis versicolor, candidiasis',
    'ketoprofen' : 'NSAID - pain and inflammation in RA, OA and AS, dysmenorrhoea, acute gout',
    'ketorolac' : 'NSAID - acute post-op pain and inflammation',
    'ketotifen' : 'sedating antihistamines - allergic reactions',
    'labetalol' : 'alpha and beta blockers - anaesthesia, hypertension, pre-eclampsia',
    'lacidipine' : 'calcium channel blockers - hypertension',
    'lacosamide' : 'antiepileptics - focal seizures, tonic-clonic seizures',
    'lactulose' : 'osmotic laxatives - constipation, hepatic encephalopathy',
    'lamivudine' : 'antiretroviral - HIV',
    'lamotrigine' : 'antiepileptics - focal seizures, tonic-clonic seizures, seizures in lennox-gastaut syndrome, bipolar disorder',
    'lanadelumab' : 'DMARD - monoclonal antibody - hereditary angioedema',
    'lanreotide' : 'somatostatin analogues - acromegaly, neuroendocrine tumours',
    'lansoprazole' : 'PPI - pUD, prophylaxis of NSAID associated ulcers, GORD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'lanthanum' : 'phosphate binders - hyperphosphataemia',
    'lapatinib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'laronidase' : 'enzymes - mucopolysaccharidosis',
    'latanoprost' : 'prostaglandins and analogues - ocular hypertension, chronic glaucoma',
    'leflunomide' : 'DMARD - other - RA, psoriatic arthritis, AS',
    'lenalidomide' : 'chemotherapy - thalidomides - multiple myeloma, myelodysplasia, mantle cell lymphoma, follicular lymphoma',
    'lenograstim' : 'granulocute colony stimulating factors - neutropenia',
    'lenvatinib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma',
    'letermovir' : 'antivirals - other - CMV infection and prophylaxis',
    'letrozole' : 'aromatase inhibitors - oestrogen-receptor positive breast cancer',
    'levamisole' : 'antihelmintics - roundworm infections',
    'levetiracetam' : 'antiepileptics - focal seizures, tonic-clonic seizures, myoclonic seizures, status epilepticus',
    'levocarnitine' : 'amino acids and derivatives - carnitine deficiency',
    'levofloxacin' : 'quinolone antibiotics - eye infections, COPD exacerbation, URI, H pylori, pneumonia',
    'carbidopa' : 'dopamine precursors - parkinsons disease',
    'levodopa' : 'dopamine precursors - parkinsons disease',
    'levomenthol' : 'antipruritics - pruritus',
    'levonorgestrel' : 'progestogens - contraception',
    'lidocaine' : 'local anaesthetics - CpR, ventricular arrhythmias, anaesthesia, pain relief',
    'linaclotide' : 'guanylate cyclase agonist - IBS with constipation',
    'linagliptin' : 'DPP4 inhibitors - T2DM',
    'linezolid' : 'oxazolidinone antibiotic - pneumonia, complicated skin and soft tissue infections',
    'liraglutide' : 'GLp1 receptor agonist - T2DM',
    'lisinopril' : 'ACEi - hypertension, heart failure, renal failure',
    'lithium' : 'antipsychotics, other - bipolar disorder, mania, recurrent depression',
    'lixisenatide' : 'GLp1 receptor agonist - T2DM',
    'lodoxamide' : 'mast cell stabilisers - allergic conjunctivitis',
    'lofepramine' : 'tricyclic antidepressants - depression',
    'lomitapide' : 'lipid modifying drugs - hyperlipidaemia, homozygous familial hypercholesterolaemia',
    'lomustine' : 'chemotherapy - alkylating agents - hodgkins disease, melanoma',
    'loperamide' : 'antipropulsives - diarrhoea, faecal incontinence, bowel colic in palliative care',
    'loprazolam' : 'benzodiazepines - insomnia',
    'loratadine' : 'non-sedating antihistamine - allergic reactions',
    'lorazepam' : 'benzodiazepines - anxiety, insomnia, panic attacks, sedation,status epilepticus',
    'lorlatinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'lormetazepam' : 'benzodiazepines - insomnia',
    'losartan' : 'ARB - hypertension, heart failure, diabetic nephropathy',
    'loxapine' : 'antipsychotics, first generation - agitation in schizophrenia or bipolar disorder',
    'lusutrombopag' : 'thrombopoietin receptor agonist - thrombocytopenia in chronic liver disease',
    'lutropin' : 'gonadotrophins - infertility',
    'lymecycline' : 'tetracyclines - acne vulgaris, chlamydia, rickettsia, mycoplasma',
    'macitentan' : 'endothelin receptor antagonists - pulmonary hypertension',
    'malathion' : 'parasiticides - lice, scabies',
    'mannitol' : 'mucolytics, osmotic laxatives - cerebral oedema, raised intraocular pressure, cystic fibrosis',
    'maraviroc' : 'antivirals - other - HIV infection',
    'mebendazole' : 'antihelmintics - threadworm, hookworm, roundworm infections',
    'mebeverine' : 'antispasmodics - gastrointestinal spasm, IBS',
    'mefloquine' : 'antimalarials - malaria treatment and prophylaxis',
    'melatonin' : 'non-benzodiazepine sedatives and hypnotics - insomnia, jet lag',
    'meloxicam' : 'NSAID - pain and inflammation in RA, OA and AS',
    'melphalan' : 'chemotherapy - alkylating agents - multiple myeloma, polycythaemia vera, malignant melanoma, soft tissue sarcoma',
    'memantine' : 'NMDA receptor blocker - Alzheimers disease',
    'menotrophin' : 'gonadotrophins - infertility',
    'mepolizumab' : 'DmARD - monoclonal antibody - eosinophilic asthma',
    'meptazinol' : 'opioids - pain',
    'metformin' : 'biguanides - T2DM, pCOS',
    'mercaptopurine' : 'DMARD - antimetabolites, chemotherapy - antimetabolites - crohns disease, ulcerative colitis, ALL, AML, CML',
    'meropenem' : 'carbapenem antibiotics - servere bacterial infections ',
    'mesalazine' : 'aminosalicylates - acute ulcerative colitis, maintenance of remission of ulcerative colitis',
    'mesna' : 'antidotes - cytotoxic induced urothelial toxicity',
    'metaraminol' : 'sympathomimetics - acute hypotension',
    'methadone' : 'opioids - pain, opioid dependence',
    'methocarbamol' : 'muscle relaxants - muscle spasm',
    'methotrexate' : 'DMARD - antimetabolites - crohns disease, RA, neoplastic diseases, psoriasis',
    'methoxyflurane' : 'volatile liquid anaesthetics - pain',
    'methyldopa' : 'antihypertensive, centrally acting - hypertension',
    'metoclopramide' : 'dopamine receptor antagonists - nausea and vomiting, hiccup in palliative care, acute migraine',
    'metolazone' : 'thiazide like diuretics - oedema, hypertension',
    'metreleptin' : 'hormones and analogues - leptin deficiency in lipodystrophy',
    'metronidazole' : 'antibiotics, other - anaerobic bacterial infections',
    'metyrapone' : 'enzyme inhibitors - cushings syndrome, resistant oedema',
    'mexiletine' : 'sodium channel blockers - ventricular arrhythmias',
    'micafungin' : 'antifungals - candidiasis',
    'miconazole' : 'antifungals - fungal skin infections, candidiasis',
    'midazolam' : 'benzodiazepines - status epilepticus, sedation, restlessness in palliative care',
    'midostaurin' : 'chemotherapy - protein kinase inhibitor - AML, mastocytosis, mast cell leukaemia',
    'mifamurtide' : 'immunostimulants - osteosarcoma',
    'mifepristone' : 'progesterone receptor modulators - termination of pregnancy',
    'migalastat' : '?? - fabrys disease',
    'miglustat' : 'glucosylceramide synthase inhibitors - gauchers disease, niemann-pick disease',
    'milrinone' : 'PDE3 inhibitor - acute heart failure',
    'minocycline' : 'tetracyclines - acne vulgaris, chlamydia, rickettsia, mycoplasma',
    'minoxidil' : 'potassium channel openers - severe hypertension',
    'mirabegron' : 'beta 3 agonists - urinary frequency, urgency and incontinence',
    'mirtazapine' : 'tetracyclic antidepressants - major depression',
    'misoprostol' : 'prostaglandins and analogues - termination of pregnancy',
    'mitomycin' : 'chemotherapy - cytotixc antibiotics - bladder tumours, gastrointestinal cancer, breast cancer, non-small cell lung cancer, pancreatic cancer',
    'mitotane' : 'antineoplastics, other - adrenocortical carcinoma',
    'mitoxantrone' : 'chemotherapy - anthracyclines - metastatic breast cancer, non-hodgkins lymphoma, hepatocellular carcinoma',
    'mivacurium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'mizolastine' : 'non-sedating antihistamine - allergic reactions',
    'mobocertinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'moclobemide' : 'MAO inhibitors - depression, social anxiety disorder',
    'modafinil' : 'sympathomimetics - excessive sleepiness in narcolepsy',
    'mogamulizumab' : 'chemotherapy - monoclonal antibodies - mycosis fungiodes, sezary syndrome',
    'molnupiravir' : 'antivirals - other - COVID 19',
    'mometasone' : 'corticosteroids - asthma prophylaxis, psoriasis, inflammatory skin disorders',
    'montelukast' : 'leukotriene receptor antagonist - asthma prophylaxis',
    'morphine' : 'opioids - pain, MI, acute pulmonary oedema, breathlessness in palliative care',
    'moxifloxacin' : 'quinolone antibiotics - local infections, sinusitis, community acquired pneumonia, bronchitis exacerbation, pelvic inflammatory disease, complicated skin and soft tissue infections',
    'moxisylyte' : 'peripheral vasodilators - raynauds syndrome',
    'moxonidine' : 'antihypertensive, centrally acting - hypertension',
    'mupirocin' : 'antibiotics, other - gram positive bacterial skin infections, non-bullous impetigo',
    'nabilone' : 'cannabinoids - nausea and vomiting caused by cytotoxic chemotherapy',
    'nabumetone' : 'NSAID - pain and inflammation in OA and RA',
    'nadolol' : 'beta blocker - hypertension, angina, arrhythmias, migraine prophylaxis, thyrotoxicosis',
    'nafarelin' : 'gonadotrophin releasing hormones - endometriosis, IVF',
    'naldemedine' : 'opioid receptor antagonists - opioid induced constipation',
    'nalmefene' : 'opioid receptor antagonists - reduction of alcohol consumption in alcohol dependence',
    'naloxegol' : 'opioid receptor antagonists - opioid induced constipation',
    'naloxone' : 'antidotes, opioid receptor antagonists - opioid overdose',
    'naltrexone' : 'opioid receptor antagonists - relapse prevention in opioid and alcohol dependence',
    'neomycin' : 'aminoglycoside antibiotics - bacterial skin infections, hepatic coma',
    'naproxen' : 'NSAID - pain and inflammation in rheumatoid conditions, acute gout, acute migraine, dysmenorrhoea',
    'naratriptan' : 'triptans - acute migraine',
    'natalizumab' : 'anti-lymphocyte monoclonal antibodies - relapsing remitting MS',
    'nebivolol' : 'beta blocker - hypertension, heart failure',
    'nelarabine' : 'chemotherapy - antimetabolites - T-cell ALL and T-cell lymphoblastic lymphoma',
    'neostigmine' : 'acetylcholinesterase inhibitor - myasthenia gravis, reversal of non-depolarising neuromuscular blockade',
    'nepafenac' : 'NSAID - post operative pain',
    'neratinib' : 'chemotherapy - protein kinase inhibitor - breast cancer (HER2 +ve)',
    'netilmicin' : 'aminoglycoside antibiotics - local infections',
    'nevirapine' : 'antiretroviral - HIV infection',
    'nicorandil' : 'potassium channel openers - angina',
    'nicotinamide' : 'vitamins and analogues - inflammatory acne vulgaris',
    'nicotine' : 'nicotinic receptor agonists - smoking cessation aid',
    'nifedipine' : 'calcium channel blockers - raynauds syndrome, premature labour, hiccup in palliative care, chronic anal fissure',
    'nilotinib' : 'chemotherapy - protein kinase inhibitor - CML (philadelphia chromosome positive)',
    'nimodipine' : 'calcium channel blockers - prevention and treatment of ischaemic neurological defects following aneurysmal subarachnoid haemorrhage',
    'nintedanib' : 'chemotherapy - protein kinase inhibitor - ideopathic pulmonary fibrosis, chronic fibrosing interstitial lung disease, systemic sclerosis associated interstitial lung disease',
    'niraparib' : 'antineoplastics, other - ovarian cancer, peritoneal cancer',
    'nitrazepam' : 'benzodiazepines - insomnia',
    'nitrofurantoin' : 'antibiotics, other - LUTI',
    'nivolumab' : 'anti-pD1 monoclonal antibody - melanoma, renal cell carcinoma, non-small cell lung cancer, mesothelioma, SCC, hodgkin lympoma',
    'nizatidine' : 'H2 receptor antagonists - GORD, peptic ulcer',
    'nonoxinol' : 'spermicidal agents - contraception',
    'norethisterone' : 'progestogens - endometriosis, menorrhagia, dysmenorrhoea, contraception, breast cancer',
    'nortriptyline' : 'tricyclic antidepressants - depression, neuropathic pain',
    'nusinersen' : 'drugs for neuromuscular disorders - 5q spinal muscular atrophy',
    'nystatin' : 'antifungals - oral candidiasis, oral fungal infections',
    'obinutuzumab' : 'anti-lymphocyte monoclonal antibodies - CLL, follicular lymphomma',
    'ocrelizumab' : 'anti-lymphocyte monoclonal antibodies - MS',
    'octreotide' : 'somatostatin analogues - carcinoid syndrome, acromegaly, neuroendocrine tumours, intestinal secretions and vomiting due to bowel obstruction in palliative care',
    'odevixibat' : 'ileal bile acid transporter inhibitor - progressive familial intrahepatic cholestasis',
    'ofatumumab' : 'anti-lymphocyte monoclonal antibodies - MS',
    'ofloxacin' : 'quinolone antibiotics - local infections, UTI, LRTI, prostatitis, complicated skin infections, uncomplicated gonorrhoea, pID, chalmydia',
    'olanzapine' : 'antipsychotics, second generation - schizophrenia, mania, bipolar disorder',
    'olaparib' : 'antineoplastics, other - ovarian cancer, peritoneal cancer',
    'olmesartan' : 'ARB - hypertension, heart failure',
    'olodaterol' : 'long acting beta agonists - COPD',
    'olopatadine' : 'antihistamines - allergic conjunctivitis',
    'omalizumab' : 'DMARD - monoclonal antibody - allergic asthma, chronic spontaneous urticaria',
    'omeprazole' : 'PPI - dispepsia, pUD, prophylaxis of NSAID associated ulcers, GoRD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'ondansetron' : 'serotonin receptor antagonists - nausea and vomiting',
    'opicapone' : 'catechol-o-methyltransferase inhibitors - parkinsons disease',
    'opium' : 'opioid - acute diarrhoea',
    'oritavancin' : 'glycopeptide antibiotics - acute bacterial skin and skin structure infections',
    'orlistat' : 'antiobesity drugs - obesity',
    'oseltamivir' : 'antivirals - neuraminidase inhibitors - prevention and treatment of influenza',
    'osilodrostat' : 'enzyme inhibitors - cushings syndrome',
    'osimertinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer',
    'ospemifene' : 'oestrogen receptor modulator - vaginal atrophy in post-menopausal women',
    'oxaliplatin' : 'chemotherapy - platinum compounds - metastatic colorectal cancer',
    'oxazepam' : 'benzodiazepines - anxiety, insomnia',
    'oxcarbazepine' : 'antiepileptics - focal seizures, tonic-clonic seizures',
    'oxerutins' : '?? - oedema associated with chronic venous insufficiency',
    'oxybutynin' : 'antimuscarinics - urinary frequency, urgency and incontinence',
    'oxycodone' : 'opioids - pain',
    'oxymetholone' : 'anabolic steroids - aplastic anaemia',
    'oxytocin' : 'oxytocin and analogues - induction of labour, caesarean section, postpartum haemorrhage',
    'ozanimod' : 'Immunomodulating drugs - MS',
    'paclitaxel' : 'chemotherapy - taxanes - ovarian cancer, breast cancer, Kaposis sarcoma',
    'palbociclib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'paliperidone' : 'antipsychotics, second generation - schizophrenia, schizoaffective disorder',
    'palivizumab' : 'monoclonal antibodies - prevention of serious RSV infection in children',
    'palonosetron' : 'serotonin receptor antagonists - nausea and vomiting after chemotherapy',
    'pancreatin' : 'enzymes - pancreatic insufficiency',
    'pancuronium' : 'non-depolarising neuromuscular blockers - neuromuscular blockade during surgery and intubation',
    'panitumumab' : 'chemotherapy - monoclonal antibodies - colorectal cancer',
    'panobinostat' : 'antineoplastics, other - multiple myeloma',
    'pantoprazole' : 'PPI - PUD, prophylaxis of NSAID associated ulcers, GORD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'paracetamol' : 'analgesics, non-opiod - pain, pyrexia',
    'parecoxib' : 'NSAID - post operative pain',
    'paricalcitol' : 'vitamins and analogues - secondary hyperparathyroidism',
    'paroxetine' : 'SSRIs - depression, panic disorder, OCD, PTSD, generalised anxiety disorder',
    'pasireotide' : 'somatostatin analogues - Cushings disease, acromegaly',
    'patisiran' : 'neuroprotective drugs - polyneurpathy',
    'pazopanib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, soft tissue sarcomas',
    'pegaspargase' : 'antineoplastics, other - ALL',
    'pegcetacoplan' : 'Immunomodulating drugs - paroxysmal nocturnal haemoflobinuria',
    'pegfilgrastim' : 'granulocute colony stimulating factors - neutropenia',
    'pegvisomant' : 'hormones and analogues - acromegaly',
    'pembrolizumab' : 'anti-pD1 monoclonal antibody - melanoma, renal cell carcinoma,urothelial carcinoma,  non-small cell lung cancer, mesothelioma, SCC, hodgkin lympoma, oesophageal carcinoma, breast cancer, cervical cancer, endometrial cancer, biliary cancer',
    'pemetrexed' : 'chemotherapy - antimetabolites - mesothelioma, non-small cell lung cancer',
    'pemigatinib' : 'chemotherapy - protein kinase inhibitor - cholangiocarcinoma with FGFR2 fusion',
    'penicillamine' : 'antidotes and chelating agents - wilsons disease, severe active RA, autoimmmune hepatitis, cystinuria',
    'pentazocine' : 'opioids - pain',
    'pentostatin' : 'chemotherapy - cytotixc antibiotics - hairy cell leukaemia',
    'pentoxifylline' : 'peripheral vasodilators - PVD, venous leg ulcer',
    'perampanel' : 'antiepileptics - focal seizures, tonic-clonic seizures',
    'pericyazine' : 'antipsychotics, first generation - schizophrenia, psychoses, severe anxiety, agitation',
    'permethrin' : 'parasiticides - scabies, lice',
    'pertuzumab' : 'chemotherapy - monoclonal antibodies - breast cancer (HER2 +ve)',
    'phenelzine' : 'MAO inhibitors - depression',
    'phenindione' : 'vitamin K antagonists - prophylaxis of embolisation in AF, prosthetic heart valves',
    'phenobarbital' : 'barbituates - status epilepticus, all forms of epilepsy except typical absense seizures',
    'phenol' : 'sclerosants - haemmorrhoids',
    'phenytoin' : 'antiepileptics - focal seizures, tonic-clonic seizures, status epilepticus, seizures associated with head trauma or neurosurgery',
    'pholcodine' : 'cough suppressants - dry cough',
    'phosphate' : 'vitamins and analogues - hypophosphatemia',
    'phytomenadione' : 'antidotes and chelating agents - INR>8.0 or bleeding in patients on warfarin, reversal of anticoagulation',
    'pilocarpine' : 'parasympathomimetics - glaucoma, xerostomia, Sjogrens syndrome',
    'pimecrolimus' : 'calcineurin inhibitors - atopic eczema, psoriasis',
    'pimozide' : 'antipsychotics, first generation - schizophrenia, psychosis',
    'pindolol' : 'beta blocker - hypertension, angina',
    'pioglitazone' : 'thiazolidinedione - T2DM',
    'piracetam' : 'CNS stimulants - cortical myoclonus',
    'pirfenidone' : '?? unknown - idiopathic pulmonary fibrosis',
    'piroxicam' : 'NSAID - pain and inflammation in RA, OA and AS',
    'pitolisant' : 'CNS stimulants - narcolepsy',
    'pixantrone' : 'chemotherapy - anthracyclines - non-hodgkins B cell lymphomas',
    'pizotifen' : 'sedating antihistamines - migraine prophylaxis, cluster headache prophylaxis',
    'pomalidomide' : 'chemotherapy - thalidomides - multiple myeloma',
    'ponatinib' : 'chemotherapy - protein kinase inhibitor - CML, ALL  (philidelphia chromosome +vs)',
    'ponesimod' : 'Immunomodulating drugs - MS',
    'pralidoxime' : 'antidotes and chelating agents - adjunct in organophsphate poisoning',
    'pralsetinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with RET fusion',
    'pramipexole' : 'dopamine receptor agonists - parkinsons disease, restless legs syndrome',
    'prasterone' : 'oestrogens - vaginal atrophy in post-menopausal women',
    'prasugrel' : 'antiplatelet drugs - prevention of atherothrombotic events',
    'praziquantel' : 'antihelmintics - tapeworm infections, schistosoma infections',
    'prazosin' : 'alpha-adrenoreceptor blockers - hypertension, raynauds syndrome, BPH',
    'prednisolone' : 'corticosteroids - COPD, ARDS, asthma, suppression of inflammatory and allergic disorders, idiopathic thrombocytopenic purpura, eczema, IBD, myasthenia gravis, polymmyalgia rheymatica, vasculitis, SLE, polymyositis, anorexia in palliative care, proctitis',
    'pregabalin' : 'antiepileptics - focal seizures, neuropathic pain, generalised anxiety disorder',
    'pridinol' : 'muscle relaxants - muscle spasm',
    'primaquine' : 'antimalarials - malaria treatment',
    'primidone' : 'barbituates - all epilespty except typical absence seizures, essential tremor',
    'procarbazine' : 'antineoplastics, other - hodgkins lumphoma',
    'proflavine' : 'antiseptics - infected wounds',
    'progesterone' : 'progestogens - contraception, HRT, IVF, threatened miscarriage',
    'promazine' : 'antipsychotics, first generation - agitation and restlessness in elderly',
    'promethazine' : 'sedating antihistamines - allergic reactions, anaphylaxis, sedation',
    'propofol' : 'IV anaesthetics - induction of anaesthesia, sedation, maintenance of anaesthesia',
    'propanolol' : 'beta blocker - thyrotoxicosis, hypertension, prophylaxis of variceal bleeding, phaechromocytoma, angina, hypertrophic cardiomyopathy, anxiety tachycardia, essential tremor, migraine prophylaxis, arrhythmias',
    'pyridostigmine' : 'acetylcholinesterase inhibitor - myasthenia gravis',
    'prucalopride' : 'prokinetic agents - chronic constipation',
    'pyrazinamide' : 'antimycobacterials - TB',
    'pyrimethamine' : 'antiprotozoals - toxoplasmosis in pregnancy',
    'quetiapine' : 'antipsychotics, second generation - schizophrenia, mania, bipolar disorder, major depression',
    'quinagolide' : 'dopamine receptor agonists - hyperprolactinaemia',
    'quinapril' : 'ACEi - hypertension, heart failure',
    'quinine' : 'antimalarials - malaria, nocturnal leg cramps',
    'raltegravir' : 'antiretroviral - HIV infection',
    'raltitrexed' : 'antineoplastics, other - palliation of colorectal cancer',
    'ramipril' : 'ACEi - hypertension, heart failure, diabetic nephropathy',
    'ramucirumab' : 'chemotherapy - monoclonal antibodies - gastric or GOJ adenocarcinoma, metastatic colorectal cancer, metastatic non-small cell lung cancer',
    'ranibizumab' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, choroidal neovascularisation',
    'ranitidine' : 'H2 receptor antagonists - gastroduodenal ulceration, reflux oesophagitis, gastric acid reduction, prophylaxis of peptic ulcers',
    'ranolazine' : '?? - stable angina',
    'rasagiline' : 'MAO inhibitors - parkinsons disease',
    'rasburicase' : 'uric acid sequestrant - acute hyperuricaemia before initiation of chemotherapy in patients at risk of tumour lysis syndrome',
    'ravulizumab' : 'DMARD - monoclonal antibody - paroxysmal nocturnal haemoglobinuria, atypical haemolytic uraemic syndrome',
    'reboxetine' : 'antidepressants, other - major depression',
    'regorafenib' : 'chemotherapy - protein kinase inhibitor - colorectal cancer, hepatocellular carcinomma',
    'remdesivir' : 'antivirals - other - covid 19',
    'remifentanil' : 'opioids - analgesia and anaesthesia',
    'remimazolam' : 'benzodiazepines - sedation',
    'repaglinide' : 'insulin secretalogues - T2DM',
    'reslizumab' : 'DMARD - monoclonal antibody - severe eosinophilic asthma',
    'ribavirin' : 'antivirals - nucleoside analogues - bronchiolitis, RSV, parainfluenza, adenovirus infection in immunocompromised children',
    'ribociclib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'rifampicin' : 'rifamycin antibiotics - brucellosis, legionnaires disease, severe staphylococcal infections, endocarditis, TB, Hib prevention, meningococcal meningitis prevention, leprosy',
    'rilpivirine' : 'antiretroviral - HIV infection',
    'riluzole' : 'neuroprotective drugs - amyotrophic lateral sclerosis (ALS)',
    'rimegepant' : 'DMARD - monoclonal antibody - acute migraine, migraine prophylaxis',
    'riociguat' : 'guanylate cyclase agonist - pulmonary hypertension',
    'ripretinib' : 'chemotherapy - protein kinase inhibitor - gastrointestinal stromal tumour',
    'risankizumab' : 'DMARD - interleukin inhibitors - plaque psoriasis, psoriatic arthritis',
    'risdiplam' : 'drugs for neuromuscular disorders - 5q spinal muscular atrophy',
    'risperidone' : 'antipsychotics, second generation - schizophrenia, psychosis, mania, aggression in alzheimers',
    'ritonavir' : 'antiretroviral - HIV infection',
    'rituximab' : 'anti-lymphocyte monoclonal antibodies - RA, non-hodgkins lymphoma, CLL, granulomatosis with palyangiitis and microscopic polyangiitis, phemigus vulgaris',
    'rivaroxaban' : 'direct factor Xa inhibitor - prophylaxis of VTE, treatment of DVT/PE, prophylaxis of stroke in AF',
    'rivastigmine' : 'acetylcholinesterase inhibitor - Alzheimers disease, parkinsons disease',
    'rizatriptan' : 'triptans - acute migraine',
    'rocuronium' : 'non-depolarising neuromuscular blockers - neuromuscular blockade during surgery and intubation',
    'roflumilast' : 'PDE4 inhibitor - COPD',
    'romiplostim' : 'thrombopoietin receptor agonist - chronic immune thrombocytopenic purpura',
    'romosozumab' : 'DMARD - monoclonal antibody - osteoporosis',
    'ropinirole' : 'dopamine receptor agonists - parkinsons disease, restless legs syndrome',
    'rosuvastatin' : 'HMG-CoA reductase inhibitor - hyperlipidaemia, homozygous familial hypercholesterolaemia, secondary prevenetion of cardiovascular events',
    'rotigotine' : 'dopamine receptor agonists - parkinsons disease, restless legs syndrome',
    'roxadustat' : '?? - anaemia in CKD',
    'rucaparib' : 'antineoplastics, other - ovarian cancer, peritoneal cancer',
    'rufinamide' : 'antiepileptics - seizures in lennox-gastaut syndrome',
    'rupatadine' : 'non-sedating antihistamine - allergic reactions',
    'ruxolitinib' : 'chemotherapy - protein kinase inhibitor - splenomegaly',
    'safinamide' : 'MAO inhibitors - parkinsons disease',
    'salbutamol' : 'short acting beta agonists - asthma, premature labour, bronchospasm',
    'salmeterol' : 'long acting beta agonists - asthma, COPD, bronchospasm',
    'sarilumab' : 'DMARD - interleukin inhibitors - RA',
    'saxagliptin' : 'DPP4 inhibitors - T2DM',
    'secukinumab' : 'DMARD - interleukin inhibitors - AS, psoriatic arthritis, plaque psoriasis',
    'selenium' : 'vitamins and analogues - selenium deficiency, seborrhoeic dermatitis, pityriasis, versicolor',
    'selexipag' : 'antiplatelet drugs - pulmonary hypertension',
    'semaglutide' : 'GLp1 receptor agonist - T2DM',
    'senna' : 'stimulant laxatives - constipation',
    'sertraline' : 'SSRIs - depression, panic disorder, OCD, PTSD',
    'setmelanotide' : 'antiobesity drugs - obesity with genetic aetiology',
    'sevelamer' : 'phosphate binders - hyperphosphataemia',
    'sevoflurane' : 'volatile liquid anaesthetics - anaesthesia',
    'sildenafil' : 'PDE5 inhibitors - erectile dysfunction, pulmonary hypertension, digital ulcers in systemic sclerosis',
    'simeticone' : 'antifoaming agents - colic',
    'simvastatin' : 'HMG-CoA reductase inhibitor - hyperlipidaemia, homozygous familial hypercholesterolaemia, secondary prevenetion of cardiovascular events',
    'siponimod' : 'Immunomodulating drugs - MS',
    'sirolimus' : 'calcineurin inhibitors - transplant rejection',
    'sitagliptin' : 'DPP4 inhibitors - T2DM',
    'sofosbuvir' : 'antivirals - nucleotide analogues - chronic hepatitis C',
    'solifenacin' : 'antimuscarinics - urinary frequency, urgency and incontinence',
    'solriamfetol' : 'sympathomimetics - excessive sleepiness in narcolepsy',
    'somatropin' : 'hormones and analogues - Turner syndrome, growth hormone deficiency',
    'sorafenib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, thyroid cancer, hepatocellular carcinoma',
    'sotalol' : 'beta blocker - ventricular tachyarrhythmias, paroxysmal atrial arrhythmias, maintenance of sinus rhythm',
    'sotorasib' : 'antineoplastics, other - non-small cell lung cancer with KRAS mutation',
    'sotrovimab' : 'monoclonal antibodies - covid 19',
    'spironolactone' : 'mineralocorticoid receptor antagonists - oedema, ascites, nephrotic syndrome, heart failure, hypertension',
    'sterculia' : 'bulk forming laxative - constipation',
    'stiripentol' : 'antiepileptics - tonic-clonic seizures in Dravet syndrome',
    'streptokinase' : 'fibrinolytics (plasminogen activators) - MI, PE/DVT, central retinal venous or arterial thrombosis',
    'streptomycin' : 'aminoglycoside antibiotics - TB, enterococcal endocarditis',
    'streptozocin' : 'chemotherapy - alkylating agents - neuroendocrine tumours',
    'sucralfate' : 'metal salts - peptic ulceration, chronic gastritis, prophylaxis of stress ulceration',
    'sugammadex' : 'antidotes - reveral of neuromuscular blockade',
    'sulfadiazine' : 'sulphonamide antibiotic - prevention of rheumatic fever recurrence',
    'sulfasalazine' : 'aminosalicylates - active crohns disease, active ulverative colitis, active RA, maintenance of UC remission',
    'sulindac' : 'NSAID - pain and inflammation in rheumatoid conditions, acute gout',
    'sulpiride' : 'antipsychotics, first generation - schizophrenia',
    'sumatriptan' : 'triptans - acute migraine, cluster headache',
    'sunitinib' : 'chemotherapy - protein kinase inhibitor - gastrointestinal stromal tumours, pancreatic neuroendocrine tumours',
    'suxamethonium' : 'depolarising neuromuscular blockers - neuromuscular blockade during surgery and intubation',
    'tacalcitol' : 'vitamins and analogues - plaque psoriasis',
    'tacrolimus' : 'calcineurin inhibitors - atopic eczema, psoriasis, transplant rejection',
    'tadalafil' : 'PDE5 inhibitors - erectile dysfunction, pulmonary hypertension',
    'tafamidis' : 'neuroprotective drugs - transthyretin amyloidosis',
    'tafasitamab' : 'chemotherapy - monoclonal antibodies - diffuse large B cell lymphoma',
    'tafluprost' : 'prostaglandins and analogues - ocular hypertension, chronic glaucoma',
    'talazoparib' : 'antineoplastics, other - breast cancer',
    'tamoxifen' : 'anti-oestrogens - oestrogen receptor positive breast cancer, anovulatory infertility, gynaecomastia',
    'tamsulosin' : 'alpha-adrenoreceptor blockers - BPH',
    'tapentadol' : 'opioids - pain',
    'tazarotene' : 'retinoids - plaque psoriasis',
    'tebentafusp' : 'antineoplastics, other - uveal melanoma',
    'tedizolid' : 'oxazolidinone antibiotic - acute skin and skin structure infections',
    'teduglutide' : 'amino acids and derivatives - short bowel syndrome',
    'teicoplanin' : 'glycopeptide antibiotics - C diff, foot infections, cellulitis, complicated infections, pneumonia, endocarditis, meningitis, bacteraemia, surgical prophylaxis',
    'telmisartan' : 'ARB - hypertension, prevention of cardiovascular events',
    'temazepam' : 'benzodiazepines - insomnia, sedation',
    'temocillin' : 'penicillin antibiotics - septicaemia, UTI, LRTI caused by gram negative bacteria',
    'temozolomide' : 'chemotherapy - alkylating agents - gioblastoma multiforme',
    'temsirolimus' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, mantle cell lymphoma',
    'tenecteplase' : 'fibrinolytics (plasminogen activators) - acute MI',
    'tenoxicam' : 'NSAID - pain and inflammation in rheumatoid conditions',
    'terazosin' : 'alpha-adrenoreceptor blockers - hypertension, BPH',
    'terbinafine' : 'antifungals - tinea infections, pityriasis versicolor, cutaneous candidiasis',
    'terbutaline' : 'short acting beta agonists - asthma, premature labour',
    'teriflunomide' : 'Immunomodulating drugs - MS',
    'teriparatide' : 'parathyroid hormones and analogues - osteoporosis',
    'terlipressin' : 'ADH analogues - oesophageal variceal bleeding',
    'testosterone' : 'hormones and analogues - low libido in postmenopausal women, hypogonadism due to androgen deficiency',
    'tetrabenazine' : 'VMAT2 inhibitors - movement disorders, tardive dyskinesia',
    'tetracaine' : 'local anaesthetics - local anaesthesia of eye or before cannulation',
    'tetracycline' : 'tetracyclines - acne vulgaris, rosacea, non-gonococcal urethritis, H pylori, chlamydia, rickettsia, mycoplasma',
    'thalidomide' : 'chemotherapy - thalidomides - multiple myeloma',
    'thiopental' : 'barbituates - status epilepticus, anaesthesia',
    'thiamine' : 'vitamins and analogues - thiamine deficiency',
    'theophylline' : 'xanthines - asthma',
    'thyrotropin' : 'hormones and analogues - detection of thyroid remnants and cancer post thyroidectomy',
    'tiagabine' : 'antiepileptics - focal seizures',
    'tibolone' : 'oestrogens - osteoporosis prophylaxis',
    'ticagrelor' : 'antiplatelet drugs - prevention of atherothrombotic events',
    'tigecycline' : 'tetracyclines - complicated skin, soft tissue and intra-abdominal infections',
    'tildrakizumab' : 'DMARD - interleukin inhibitors - plaque psoriasis',
    'timolol' : 'beta blocker - hypertension, angina, migraine prophylaxis, ocular hypertension, glaucoma',
    'tioconazole' : 'antifungals - fungal nail infection',
    'tioguanine' : 'chemotherapy - antimetabolites - leukaemias',
    'tiotropium' : 'antimuscarinics - COPD',
    'tipranavir' : 'antiretroviral - HIV infection',
    'tirbanibulin' : 'chemotherapy - protein kinase inhibitor - actinic keratosis',
    'tirofiban' : 'antiplatelet drugs - NSTEMI, STEMI, unstable angina',
    'tivozanib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma',
    'tizanidine' : 'muscle relaxants - muscle spasm',
    'tobramycin' : 'aminoglycoside antibiotics - severe infections, septicaemia, meningitis, pneumonia, UTI',
    'tocilizumab' : 'DMARD - interleukin inhibitors - RA, giant cell arteritis, covid 19',
    'tofacitinib' : 'DMARD - JAK1 inhibitor - RA, psoriatic arthritis, ulcerative colitis, AS',
    'tolbutamide' : 'sulfonylureas - T2DM',
    'tolcapone' : 'catechol-o-methyltransferase inhibitors - parkinsons disease',
    'tolvaptan' : 'vasopressin receptor antagonist - autosomal dominant polycystic kidney disease, hyponatraemia secondary to SIADH',
    'topiramate' : 'antiepileptics - tonic-clonic seizures, focal seizures, seizures in lennox-gastaut syndrome, migraine prophylaxis',
    'topotecan' : 'chemotherapy - topoisomerase inhibitors - metastatic ovarian cancer, cervical cancer, small-cell lung cancer',
    'torasemide' : 'loop diuretic - oedema, hypertension',
    'toremifene' : 'anti-oestrogens - oestrogen receptor positive breast cancer',
    'trabectedin' : 'chemotherapy - plant alkaloids - soft tissue sarcoma, ovarian cancer',
    'tralokinumab' : 'DMARD - interleukin inhibitors - atopic eczema',
    'tramadol' : 'opioids - pain',
    'trametinib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma',
    'trandolapril' : 'ACEi - hypertension',
    'trastuzumab' : 'chemotherapy - monoclonal antibodies - breast cancer (HER2 +ve)',
    'trazodone' : 'antidepressants, other - depression, anxiety',
    'travoprost' : 'prostaglandins and analogues - ocular hypertension, chronic glaucoma',
    'treosulfan' : 'chemotherapy - alkylating agents - ovarian cancer',
    'treprostinil' : 'prostaglandins and analogues - pulmonary hypertension',
    'tretinoin' : 'retinoids - acute promyelocytic leukaemia',
    'triamterene' : 'potassium sparing diuretics - oedema, potassium conservation with thiazide and loop diuretics',
    'trientine' : 'antidotes and chelating agents - wilsons disease',
    'trifarotene' : 'retinoids - acne vulgaris',
    'trimethoprim' : 'antibiotics, other - RTI, UTI, pJp, acne vulgaris, shigellosis, diverticulitis',
    'trimipramine' : 'tricyclic antidepressants - depression',
    'triptorelin' : 'gonadotrophin releasing hormones - endometriosis, prostate cancer',
    'tropicamide' : 'antimuscarinics - fundoscopy',
    'tryptophan' : 'antidepressants, other - depression',
    'tucatinib' : 'chemotherapy - protein kinase inhibitor - breast cancer (HER2 +ve)',
    'ulipristal' : 'progesterone receptor modulators - emergency contraception, uterine fibroids',
    'umeclidinium' : 'antimuscarinics - COPD',
    'upadacitinib' : 'DMARD - JAK1 inhibitor - RA, psoriatic arthritis, atopic eczema, AS',
    'urofollitropin' : 'gonadotrophins - infertility',
    'urokinase' : 'fibrinolytics (plasminogen activators) - DVT, pE, occlussive pAD',
    'ustekinumab' : 'DMARD - interleukin inhibitors - IBD, psoriatic arthritis, plaque psoriasis',
    'valaciclovir' : 'antivirals - nucleoside analogues - HSv, HZV, VZV infection',
    'valganciclovir' : 'antivirals - nucleoside analogues - CMV retinitis, prevention of CMV post-transplant',
    'valsartan' : 'ARB - hypertension, heart failure',
    'vancomycin' : 'glycopeptide antibiotics - C diff, foot infections, cellulitis, complicated infections, pneumonia, endocarditis, meningitis, bacteraemia, surgical prophylaxis',
    'vandetanib' : 'chemotherapy - protein kinase inhibitor - medullary thryroid cancer',
    'verapamil' : 'calcium channel blockers - supraventricular arrhythmias, tachyarrhythmias, angina, hypertension, prophylaxis of cluster headache',
    'vecuronium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'vardenafil' : 'PDE5 inhibitors - erectile dysfunction',
    'varenicline' : 'Nicotine receptor agonist - smoking cessation',
    'vasopressin' : 'ADH analogues - pituitary diabetes insipidus, oesophageal variceal bleeding',
    'vedolizumab' : 'anti-lymphocyte monoclonal antibodies - crohns disease, ulcerative colitis',
    'vemurafenib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma',
    'venetoclax' : 'antineoplastics, other - CLL, AML',
    'venlafaxine' : 'SNRI - depression, generalised anxiety disorder, social anxiety disorder, panic disorder',
    'vigabatrin' : 'antiepileptics - focal seizures',
    'vildagliptin' : 'DPP4 inhibitors - T2DM',
    'vincristine' : 'chemotherapy - vinca alkaloids - leukaemias, lymphomas, breast cancer, lung cancer',
    'vinorelbine' : 'chemotherapy - vinca alkaloids - breast cancer, non-small cell lung cancer',
    'vismodegib' : 'antineoplastics, other - metastatic basal cell carcinoma',
    'voriconazole' : 'antifungals - invasive asperigillosis, invasive candidiasis',
    'vortioxetine' : 'serotonin reuptake inhibitor, partial serotonin agonists - major depression',
    'voxelotor' : 'HbS polymerisation inhibitors - sickle cell disease',
    'warfarin' : 'vitamin K antagonists - prophylaxis of embolisation in AF, prosthetic heart valves',
    'xipamide' : 'thiazide like diuretics - oedema, hypertension',
    'zanamivir' : 'antivirals - neuraminidase inhibitors - influenza',
    'zanubrutinib' : 'chemotherapy - protein kinase inhibitor - Waldenstroms macroglobinaemia',
    'zidovudine' : 'antiretroviral - HIV infection',
    'zolmitriptan' : 'triptans - acute migraine, cluster headache',
    'zonisamide' : 'antiepileptics - focal seizures',
    'zopiclone' : 'non-benzodiazepine sedatives and hypnotics - insomnia',
    'zuclopenthixol' : 'antipsychotics, first generation - schizophrenia'
}

def choose_drug():
    drug, indicationclass = rdm.choice(list(drugs_master.items()))
    while len(drug)<14:
        drug += '*'
    return drug, indicationclass

def ask_input(dummy=None):
    while True:
        dummy = input("Enter drug : ")
        if type(dummy) != str:
            print('Invalid Entry')
            continue
        elif len(dummy) > 14:
            print('Drug name too long, maximum 14 letters please')
            continue
        elif dummy.lower() not in drugs_master.keys():
            print('Drug not in list, check spelling')
            continue
        else:
            while len(dummy)<14:
                dummy+='*'
            return dummy.upper()

def build_df(attempt, guess_arr):
    cols = ['L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9', 'L10', 'L11', 'L12', 'L13', 'L14']
    idx = ['TRY_' + str(attempt +1)]
    
    df = pd.DataFrame(guess_arr).T
    df.columns = cols
    df.index = idx
    
    return df

def mark_letters(guess_idx):
    final = []
    for items in guess_idx:
        if items[2] == 'YES':
            final.append(items[0])
        elif items[2] == 'EX':
            final.append(items[0]+' ')
        else:
            final.append(items[0].lower())
    return final

def play():
    true_drug, classindication = choose_drug()
    print('HINT :  DRUG CLASS - INDICATION')
    print(classindication)
    print('   ')
    
    true_arr = np.array(list(true_drug.upper()))
    true_idx = [[item, idx, None] for idx, item in enumerate(true_arr)]
    
    letters_notguessed = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
    
    attempt=0
    guess_store = []
    
    while attempt <9:
        print(r'Letters not guessed: ')
        print(letters_notguessed)
        guess_drug = ask_input()
        guess_arr = np.array(list(guess_drug))
        guess_idx = [[item, idx, None] for idx, item in enumerate(guess_arr)]
        
        matched = []
        existing = []
        matching = np.where(true_arr == guess_arr)[0]
        
        ii = 0
        while ii < 14:
            try: 
                letters_notguessed.remove(guess_drug[ii])
                ii += 1
            except: 
                ii += 1
        
        for item in matching:
            matched.append(guess_idx[item][0])
            guess_idx[item][2], true_idx[item][2] = 'YES', 'YES'
            
        rem_guess = [item for item in guess_idx if item[2] != 'YES']
        rem_true = [item for item in true_idx if item[2] != 'YES']
        
        for guess in rem_guess:
            for true in rem_true:
                if guess[0] == true[0]:
                    if list(true_arr).count(guess[0]) > (matched.count(guess[0]) + existing.count(guess[0])):
                        existing.append(guess[0])
                        guess[2], true[2] = 'EX', 'EX'
                    else:
                        continue

        final = mark_letters(guess_idx)
        
        guess_df = build_df(attempt, final)
        guess_store.append(guess_df)
        new_df = pd.concat(guess_store)
        
        
        def colour_correct(value):
            if value == value.upper() and len(value) == 1:
                colour = 'green'
            elif len(value) == 2:
                colour = 'orange'
            else:
                colour = 'black'            
            return 'color: %s' % colour
        
        s = new_df.style.applymap(colour_correct)
        display(s)
        
        if guess_drug.lower() == true_drug.lower():
            drugname = true_drug.strip('*')
            print('you win!')
            break
        else:
            print( str(8-attempt)+' guesses remaining...')
            attempt += 1
            
            if attempt == 9:
                drugname = true_drug.strip('*')
                print(f'Sorry, the drug was {drugname.upper()}')
                break


if __name__ == '__main__':
    play()