drugs_master = {
    #    'drugname' : 'drugclass - drugindication'
    'Abacavir' : 'antiretrovirals - HIV infection'
    'Abatacept' : 'T-cell activation innhibitors - rheumatoid arthritis, psoriatic arthritis',
    'Abemaciclib' : 'chemotherapy - protein kinase inhibitor - breast cancer',
    'Abrocitinib' : 'DMARD - JAK1 inhibitor - severe atopic eczema',
    'Acalabrutinib' : 'chemotherapy - protein kinase inhibitor - CLL',
    'Acarbose' : 'intestinal glucosidase inhibitor - T2DM',
    'Acebutolol' : 'beta blocker - hypertension, angina, arrhythmias',
    'Aceclofenac' : 'NSAID - pain and inflammation in RA, OA and AS',
    'Acenocoumarol' : 'vitamin K antagonist - prophylaxis of embolisation, VTE and TIA',
    'Acetazolamide' : 'carbonic anhydrase inhibitor - glaucoma',
    'Acetylcysteine' : 'antidote, mucolytic - paracetamol overdose, tear deficiency',
    'Aciclovir' : 'antivirals - nucleoside analogues - HSV, VZV infection',
    'Acipimox' : 'nicotinic acid derivatives - hyperlipidaemia',
    'Acitretin' : 'retinoids - severe psoriasis',
    'Acrivastine' : 'non-sedating antihistamine - allergic reactions',
    'Adalimumab' : 'DMARD - TNF-a inhibitor - plaque psoriasis, RA, psoriatic arthritis, crohn's disease, ulcerative colitis, uveitis',
    'Adapalene' : 'retinoids - acne vulgaris',
    'Adenosine' : 'antiarrhythmics - paroxysmal SVT, WPW syndrome',
    'Adrenaline' : 'alpha and beta agonists - CPR, acute hypotension, anaphylaxis',
    'Afatinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'Aflibercept' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, ',
    'agratoban' : 'direct thrombin inhibitors - unstable angina/NSTEMI, STEMI PCI',
    'Agomelatine' : 'melatonin receptor agonists, serotonin receptor antagonist - major depression',
    'Alectinib' : 'chemotherapy - protein kinase inhibitor - ALK+ non-small cell lung cancer',
    'Alemtuzumab' : 'anti-lymphocyte monoclonal antibodies - MS',
    'Alfacalcidol' : 'vitamins and analogues - vitamin D deficiency',
    'Alfentanil' : 'opioids - ventilation, pain in palliative care',
    'Alirocumab' : 'lipid modigying drugs - hyperlipidaemia',
    'Aliskiren' : 'renin inhibitors - hypertension',
    'Alitretinoin' : 'retinoids - severe hand eczema',
    'Allopurinol' : 'xanthine oxidase inhibitors - gout prophylaxis',
    'Almotriptan' : 'triptans - acute migraine',
    'Alogliptin' : 'DPP4 inhibitor - T2DM',
    'Alpelisib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'Alprazolam' : 'benzodiazepines - anxiety',
    'Alprostadil' : 'prostaglandins and analogues - erectile dysfunction',
    'Alteplase' : 'fibrinolytics (plasminogen activators) - acute MI, PE, acute ischaemic stroke',
    'Ambrisentan' : 'endothelin receptor antagonists - pulmonary hypertension',
    'Amifampridine' : 'cholinergic receptor stimulators - Lambert-Eaton myasthenic syndrome',
    'Amikacin' : 'aminoglycosides - gram negative bacterial infections, prostatitis, pyelonephritis',
    'Aminophylline' : 'xanthines - severe acute asthma, severe acute exacerbation of COPD',
    'amiodarones' : 'antiarrhythmics, class III - arrhytmmias, VF or pulseless VT in CPR',
    'Amisulpride' : 'antipsychotics, second generation - schizophrenia',
    'amitriptyline' : 'tricyclic antidepressants - depression, neuropathic pain, abdominal pain, migraine prophylaxis',
    'Amivantamab' : 'anti-EGFR monoclonal antibodies - non-small cell lung cancer with EGFR mutations',
    'Amlodipine' : 'calcium channel blockers - angina, hypertension',
    'Amorolfine' : 'antifungals - fungal nail infection',
    'Amoxicillin' : 'penicillins - oral infections, UTI, community acquired pneumonia, COPD exacerbation, otis media, diverticulitis, H pylori eradication, endocarditis',
    'Ampicillin' : 'penicillins - bronchitis, UTI, otis media, sinusitis, community acquired pneumonia, endocarditis',
    'Amsacrine' : 'antineoplastics, other - acute leukaemia',
    'Anakinra' : 'DMARD - interleukin inhibitors - rheumatoid arthritis, Still's disease',
    'Anastrozole' : 'aromatase inhibitors - adjuvant in oestrogen-receptor positive breast cancer',
    'Anidulafungin' : 'echinocandin antifungals - invasive candidiasis',
    'Apalutamide' : 'androgen receptor inhibitors - prostate cancer',
    'Apixaban' : 'direct factor Xa inhibitor - VTE/PE prophylaxis',
    'Apraclonidine' : 'alpha 2 receptor agonist - glaucoma',
    'Apremilast' : 'PDE4 inhibitor - psoriatic arthritis, plaque psoriasis',
    'Aprepitant' : 'neurokinin receptor antagonists - antiemetic - chemotherapy associated nausea and vomiting',
    'Aripiprazole' : 'antipsychotics, second generation - schizophrenia',
    'Asciminib' : 'chemotherapy - protein kinase inhibitor - CML (philadelphia chromosome positive)',
    'Asenapine' : 'antipsychotics, second generation - mania in bipolar disorder',
    'Asparaginase' : 'antineoplastics, other - ALL',
    'Aspirin' : 'NSAID, antiplatelet drugs - pain, secondary prevention in CVD/DVT/PE, TIA, STEMI, NSTEMI, AF',
    'Ataluren' : 'dystrophin synthesis restorer - DMD',
    'Atazanavir' : 'antiretroviral - HIV infection',
    'Atenolol' : 'beta blocker - hypertension, angina, arrhythmias, migraine prophylaxis',
    'Atezolizumab' : 'anti-PD-L1 monoclonal antibody - urothelial carcinoma, lung cancer, breast cancer, hepatocellular carcinoma',
    'Atomoxetine' : 'sympathomimetics - ADHD',
    'Atorvastatin' : 'HMG CoA reductase inhibitors - hyperlipidaemia, secondary prevention of CVD',
    'Atovaquone' : 'antiprotozoals - pneumocystis pneumonia',
    'Atracurium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'Atropine' : 'antimuscarinics - organophosphate poisoning, bradycardia',
    'Avacopan' : 'Immunomodulating drugs - granulomatosis with polyangiitis, microscopic polyangiitis',
    'Avanafil' : 'PDE5 inhibitors - erectile dysfunction',
    'Avapritinib' : 'chemotherapy - protein kinase inhibitor - gastro-intestinal stromal tumours',
    'Avelumab' : 'anti-PD-L1 monoclonal antibody - renal. cell carcinoma, merkel cell carcinoma, urothelial carcinoma',
    'Axitinib' : 'chemotherapy - protein kinase inhibitor - renal. cell carcinoma',
    'Azacitidine' : 'chemotherapy - antimetabolites - myelodysplastic syndrome, CML, AML',
    'Azathioprine' : 'DMARD - antimetabolite - crohn's disease, RA, SLE, polymyositis, transplant rejection suppression, myasthenia gravis',
    'Azithromycin' : 'macrolide antibiotics - GAS prevention, URTI, otis media, skin infections, chlamydia, conorrhoea, community acquired pneumonia',
    'Aztreonam' : 'betalactam antibiotic - gram negative bacterial infections, prostatitis, pyelonephritis',
    'Baclofen' : 'muscle relaxants - muscle spasm, hiccup in palliative care',
    'Baricitinib' : 'DMARD - JAK1 inhibitor - RA, atopic eczema',
    'Basiliximab' : 'anti-lymphocyte monoclonal antibodies - transplant rejection prophylaxis',
    'Bedaquiline' : 'antimycobacterials - multi-drug resistant pulmonary TB',
    'Belatacept' : 'T-cell activation innhibitors - transplant rejection prophylaxis',
    'Belimumab' : 'anti-lymphocyte monoclonal antibodies - SLE',
    'Benperidol' : 'antipsychotics, first generation - deviant antisocial sexual behaviour',
    'Benralizumab' : 'anti-IL5 monoclonal antibodies - severe eosinophilic asthma',
    'Berotralstat' : 'plasma kallikrein inhibitor - hereditary angioedema',
    'Betaine' : '? - homocystinuria',
    'Betamethasone' : 'corticosteroids - inflammation, immunosuppression',
    'Betaxolol' : 'beta blocker - ocular hypertension, chronic glaucoma',
    'Bevacizumab' : 'VEGF inhibitors - colorectal, breast, renal cell, lung, ovarian, cervical, hepatocellular cancers',
    'Bexarotene' : 'chemotherapy - retinoids - cutaneous T-cell lymphoma',
    'Bezafibrate' : 'fibrates - hyperlipidaemia',
    'Bezlotoxumab' : 'antitoxins - C diff prophylaxis',
    'Bicalutamide' : 'androgen receptor inhibitors - prostate cancer',
    'Bilastine' : 'non-sedating antihistamine - allergic reactions',
    'Bimatoprost' : 'prostamides - ocular hypertension, chronic glaucoma',
    'Bimekizumab' : 'DMARD - interleukin inhibitors - Plaque psoriasis',
    'Binimetinib' : 'chemotherapy - protein kinase inhibitor - BRAF +ve metastatic melanoma',
    'Bisacodyl' : 'stimulant laxatives - Constipation',
    'Bivalirudin' : 'direct thrombin inhibitors - unstable angina/NSTEMI, STEMI PCI',
    'Bleomycin' : 'chemotherapy - cytotixc antibiotics - SCC, metastatic germ cell cancer, non-hodgkins lymphoma',
    'Blinatumomab' : 'anti-lymphocyte monoclonal antibodies - ALL (Philidelphia chromosome -ve)',
    'Bortezomib' : 'chemotherapy - proteasome inhibitors - multiple myeloma, mantle cell lymphoma',
    'Bosentan' : 'endothelin receptor antagonists - pulmonary hypertension',
    'Bosutinib' : 'chemotherapy - protein kinase inhibitor - CML (philadelphia chromosome positive)',
    'Brigatinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'Brinzolamide' : 'carbonic anhydrase inhibitor - ocular hypertension, chronic glaucoma',
    'Brivaracetam' : 'antiepileptics - focal seizures',
    'Brodalumab' : 'DMARD - interleukin inhibitors - plaque psoriasis',
    'Brolucizumab' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, ',
    'Bromfenac' : 'NSAID - post-op inflamation',
    'Bromocriptine' : 'dopamine receptor agonists - galactorrhoea, acromegaly, prolactinoma, parkinsons disease',
    'Budesonide' : 'corticosteroids - asthmma, allergic rhinitis, nasal polyps',
    'Bumetanide' : 'loop diuretic - oedema',
    'Buprenorphine' : 'opioid receptor antagonists - pain, opioid dependence',
    'Buserelin' : 'gonadotrophin releasing hormones - endometriosis, IVF, prostate cancer',
    'Busulfan' : 'chemotherapy - alkylating agents - CML',
    'Cabazitaxel' : 'chemotherapy - taxanes - prostate cancer',
    'Cabergoline' : 'dopamine receptor agonists - galactorrhoea, parkinsons disease',
    'Cabotegravir' : 'antiretroviral - HIV infection',
    'Cabozantinib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, medullary thyroid cancer, hepatocellular carcinoma',
    'Calcipotriol' : 'vitamins and analogues - Plaque psoriasis',
    'Calcitriol' : 'vitamins and analogues - plaque psoriasis, renal osteodystrophy, osteoporosis',
    'Canagliflozin' : 'SGLT2 inhibitors - T2DM',
    'Canakinumab' : 'DMARD - interleukin inhibitors - gouty arthritis, familial mediterranean fever, stills disease, cryopyrin period syndrome',
    'Candesartan' : 'ARB - hypertension, heart failure',
    'Cangrelor' : 'antiplatelet drugs - thrombosis prophylaxis in PCI',
    'Cannabidiol' : 'antiepileptics - seizures associated with Lennox-gastaut syndrome, Dravet syndrome, tuberous sclerosis complex',
    'Capecitabine' : 'chemotherapy - antimetabolites - colorectal cancer, gastric cancer, breast cancer',
    'Caplacizumab' : 'antiplatelet monoclonal antibody - acquired thrombotic thrombocytopenic purpura',
    'Capreomycin' : 'antimycobacterials - TB',
    'Capsaicin' : 'plant alkaloids - neuropathic pain',
    'Captopril' : 'ACEi - hypertension, heart failure, diabetic nephropathy',
    'Carbamazepine' : 'antiepileptics - tonic-clonic seizures, trigeminal neuralgia, bipolar disorder, diabetic neuropathy',
    'Carbimazole' : '?? - hyperthyroidism',
    'Carbocisteine' : 'mucolytics - excess sputum',
    'Carbomers' : 'ocular lubricants - dry eyes',
    'Carboplatin' : 'chemotherapy - platinum compounds - ovarian cancer, small cell lung cancer, seminoma testicular germ cell tumours',
    'Carboprost' : 'prostaglandins and analogues - postpartum haemorrhage',
    'Carfilzomib' : 'chemotherapy - proteasome inhibitors - multiple myeloma',
    'Cariprazine' : 'antipsychotics, second generation - schizophrenia',
    'Carmustine' : 'chemotherapy - alkylating agents - brain tumours, multiple myeloma, non-hodgkins lymphoma, hodgkins disease, glioblastoma',
    'Carvedilol' : 'alpha and beta blockers - hypertension, angina, heart failure',
    'Caspofungin' : 'antifungals - invasive candidiasis, invasive asperfillosis',
    'Cefaclor' : 'cephalosporin antibiotics - bacterial infections, pneumonia, LUTI',
    'Cefadroxil' : 'cephalosporin antibiotics - bacterial infections, skin and soft tissue infection, LUTI',
    'Cefalexin' : 'cephalosporin antibiotics - bacterial infections, hospital acquired pneumonia, diverticulitis, UTI, pyelonephritis',
    'Cefazolin' : 'cephalosporin antibiotics - bacterial infections, skin and soft tissue infection, surgical prophylaxis, joint and bone infection',
    'Cefepime' : 'cephalosporin antibiotics - bacterial infections, LUTI',
    'Cefixime' : 'cephalosporin antibiotics - bacterial infections, gonnorrhoea',
    'Cefotaxime' : 'cephalosporin antibiotics - bacterial infections, gonnorrhoea, meningitis',
    'Cefoxitin' : 'cephalosporin antibiotics - bacterial infections, UTI',
    'Cefradine' : 'cephalosporin antibiotics - bacterial infections, surgical prophylaxis',
    'Ceftazidime' : 'cephalosporin antibiotics - bacterial infections, hospital acquired pneumonia, meningitis, febrile neutropenia, septicaemia',
    'Ceftobiprole' : 'cephalosporin antibiotics - pneumonia ',
    'Ceftriaxone' : 'cephalosporin antibiotics - bacterial infections, pneumonia, UTI, COPD exacerbation, skin and soft tissue infections, prophylaxis from bites, meningitis, endocarditis, surgical prophylaxis, fonorrhoea',
    'Cefuroxime' : 'cephalosporin antibiotics - bacterial infections, pneumonia, cellulitis, bite prophylaxis, divertiulitis, surgical prophylaxis, UTI',
    'Celecoxib' : 'NSAID - pain and inflammation in RA, OA and AS',
    'Cemiplimab' : 'anti-PD1 monoclonal antibody - SCC',
    'Cenobamate' : 'antiepileptics - focal seizures',
    'Ceritinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'Cetrorelix' : 'anti-gonadotrophin releasing hormones - infertility',
    'cetirizine' : 'non-sedating antihistamine - allergic reactions',
    'Cetuximab' : 'chemotherapy - monoclonal antibodies - colorectal cancer, SCC',
    'Chlorambucil' : 'chemotherapy - alkylating agents - lymphoma, CLL, CML',
    'Chlorhexidine' : 'antiseptics - oral candidiasis, gingivitis, stomatitis, aphthous ulcers, ',
    'Chlormethine' : 'chemotherapy - alkylating agents - mycosis fungoides',
    'Chloroquine' : 'antimalarials - RA, SLE, malaria prophylaxis and treatmment',
    'Chlortalidone' : 'thiazide like diuretics - ascites, hypertension, heart failure, diabetes insipidus',
    'Ciclesonide' : 'corticosteroids - asthma',
    'Ciclosporin' : 'calcineurin inhibitors - nephrotic syndrome, transplant rejection, UC , psoriasis, dermatitis, RA',
    'Cilostazol' : 'antiplatelet drugs - intermittent claudication',
    'Cimetidine' : 'H2 receptor antagonists - gastroduodenal ulceration, reflux oesophagitis, gastric acid reduction',
    'Cinacalcet' : 'Bone resorption inhibitors - secondary hyperparathyroidism, hypercalcaemia in parathyroid carcinoma, primary hyperparathyroidism',
    'Cinnarizine' : 'sedating antihistamines - vestibular disorders, motion sickness, ',
    'Ciprofibrate' : 'fibrates - hyperlipidaemia',
    'Ciprofloxacin' : 'quinolone antibiotics - UTI, meningitis prophylaxis, anthrax, RTI, diverticulitis, eye infections',
    'Cisatracurium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'Cisplatin' : 'chemotherapy - platinum compounds - testicular, lung, cervical, bladder, head and neck, and ovarian cancer',
    'Citalopram' : 'SSRIs - depression, panic disorder',
    'Cladribine' : 'chemotherapy - antimetabolites - leukaemia, relapsing remitting MS',
    'Clarithromycin' : 'macrolide antibiotics - skin and soft tissue infections, pneumonia, RTI, COPD exacerbation, H pylori, sinusitis, otis media',
    'Clemastine' : 'sedating antihistamines - allergic reactions',
    'Clindamycin' : 'lincosamides - staphylococcal infections, MRSA, skin and soft tissue infections',
    'Clobazam' : 'benzodiazepines - anxiety',
    'Clofazimine' : 'antimycobacterials, antimetabolites - leprosy',
    'Clomethiazole' : 'non-benzodiazepine sedatives and hypnotics - insomnia, agitation, alcohol withdrawal',
    'Clonazepam' : 'benzodiazepines - anxiety, epilepsy',
    'Clopidogrel' : 'antiplatelet drugs - atherothrombosis prvention, TIA, MI, AF',
    'Clotrimazole' : 'antifungals - fungal skin infections, candidiasis',
    'Clozapine' : 'antipsychotics, second generation - schizophrenia, psychosis in parkinsons disease',
    'Cobimetinib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma',
    'Colchicine' : 'plant alkaloids - acute gout, familial mediterranean fever prophylaxis',
    'Colecalciferol' : 'vitamins and analogues - vitamin D deficiency',
    'Colestyramine' : 'bile acid sequestrants - hyperlipidaemia, secondary prevention of CVD, diarrhoea',
    'codeine' : 'opioids - pain',
    'Crisantaspase' : 'antineoplastics, other - ALL',
    'Crizanlizumab' : 'DMARD - monoclonal antibody - sickle cell disease',
    'Crizotinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'Crotamiton' : 'antipruritics - pruritus',
    'Cyanocobalamin' : 'vitamins and analogues - B12 deficiency, pernicious anaemia',
    'Cyclizine' : 'antihistamines - nausea and vomiting in paliative care, motion sickness, vertigo',
    'Cycloserine' : 'antimycobacterials - TB',
    'Cytarabine' : 'chemotherapy - antimetabolites - ALL',
    'dabigatran' : 'direct thrombin inhibitors - unstable angina/NSTEMI, STEMI PCI',
    'Dabrafenib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma (BRAF +ve)',
    'Dacarbazine' : 'chemotherapy - alkylating agents - metastatic melanoma, soft tissue sarcomas, hodgkins disease',
    'Dacomitinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'Dalteparin' : 'heparins - DVT/PE treatment',
    'Dalbavancin ' : 'glycopeptide antibiotics - skin and soft tissue infections',
    'Dapagliflozin' : 'SGLT2 inhibitors - T2DM, heart falure, CKD',
    'Dapoxetine' : 'SSRIs - premature ejaculation',
    'Dapsone' : 'antimycobacterials - leprosy, dermatitis herperiformis, PJP',
    'dantrolene' : 'antispasmodics - msucle cramps in MND, severe spasticity, malignant hyperthermia',
    'dabigatran' : 'direct thrombin inhibitors - VTE prophylaxis, DVT/PE treatment and prophylaxis, embolic prophylaxis',
    'darbopoetin' : 'epoetins - anaemia in chronic renal failure',
    'Daptomycin' : 'lipopeptide antibiotic - complicated gram positive infections',
    'Daratumumab' : 'chemotherapy - monoclonal antibodies - multiple myeloma, light chain amyloidosis',
    'Darifenacin' : 'antimuscarinics - urinary frequency, urgency and incontinence',
    'Darolutamide' : 'androgen receptor inhibitors - prostate cancer',
    'Darunavir' : 'antiretroviral - HIV infection',
    'Dasatinib' : 'chemotherapy - protein kinase inhibitor - CML, ALL',
    'Daunorubicin' : 'chemotherapy - anthracyclines - AML, ALL, Kaposis sarcoma',
    'Deferasirox' : 'iron cheletors - chronic iron overload',
    'Deferiprone' : 'iron cheletors - thalassaemia iron overload',
    'Deflazacort' : 'corticosteroids - suppression of inflammatory and allergic disorders',
    'Degarelix' : 'anti-gonadotrophin releasing hormones - prostate cancer',
    'Delafloxacin' : 'quinolone antibiotics - skin and soft tissue infections',
    'Delamanid' : 'antimycobacterials - TB',
    'Denosumab' : 'DMARD - monoclonal antibody - osteoporosis',
    'Desflurane' : 'volatile liquid anaesthetics - anaesthesia',
    'Desloratadine' : 'non-sedating antihistamine - allergic reactions',
    'Desmopressin' : 'ADH analogues - diabetes insipidus, nocturnal enuresis, polyuria and polydipsia, haemophilia, von-Willebrands disease',
    'Desogestrel' : 'progestogens - contraception',
    'Dexamethasone' : 'corticosteroids - suppression of inflammatory and allergic disorders, inflammation, macular oedema, croup, congenital adrenal hyperplasia, anorexia in paliative care, pain in paliative care, cerebral oedema, preterm labour',
    'Dexketoprofen' : 'NSAID - pain',
    'diamorphine' : 'opioids - pain, acute pulmonary oedema, MI',
    'Diazepam' : 'benzodiazepines - muscle spasm, tetanus, anxiety, insomnia, acute alcohol withdrawal, sedation, status epilepticus, dyspnoea in paliative care',
    'Diazoxide' : 'glycogenolytic hormones - chronic intractable hypoglycaemia',
    'Diclofenac' : 'NSAID - pain following dental treatment',
    'Dienogest' : 'progestogens - endometriosis',
    'Difelikefalin' : 'antipruritics - pruritus',
    'Digoxin' : 'cardiac glycosides - atrial fibrillation or flutter, heart failure',
    'diltiazem' : 'calcium channel blockers - angina, hypertension, chronic anal fissure',
    'dihydrocodeine' : 'opioids - pain',
    'Dimeticone' : 'parasiticides - head lice',
    'Dinoprostone' : 'prostaglandins and analogues - induction of labour',
    'Dipyridamole' : 'antiplatelet drugs - prevention of stroke, TIA, thromboembolism',
    'Disopyramide' : 'antiarrhythmic agents - arrhythmias, maintenance of sinus rhythm',
    'Disulfiram' : '?? - alcohol dependence',
    'Dithranol' : 'antracen derivatives - chronic psoriasis',
    'docusate' : 'stimulant laxatives - constipation',
    'Dobutamine' : 'sympathomimetics - inotropic support in infarction, shock, cardiomyopathies, and cardiac stress testing',
    'Docetaxel' : 'chemotherapy - taxanes - breast cancer, non-small cell lung cancer, prostate cancer, gastric adenocarcinoma',
    'docusate' : 'softening laxatives - chronic constipation',
    'Dolutegravir' : 'antiretroviral - HIV infection',
    'Domperidone' : 'dopamine receptor antagonists - nausea and vomiting in paliative care',
    'Donepezil' : 'acetylcholinesterase inhibitor - Alzheimers disease',
    'Dopamine' : 'sympathomimetics - cardgiogenic shock',
    'Doravirine' : 'antiretroviral - HIV infection',
    'Dorzolamide' : 'carbonic anhydrase inhibitor - ocular hypertension, chronic glaucoma',
    'Dostarlimab' : 'anti-PD1 monoclonal antibody - endometrial cancer',
    'Doxazosin' : 'alpha-adrenoreceptor blockers - hypertension, BPH',
    'Doxepin' : 'antipruritics, tricyclic antidepressants - pruritus, sedation in depression',
    'Doxycycline' : 'tetracyclines - chlamydia, rickettsia, mycoplasma, other infections',
    'Dronedarone' : 'antiarrhythmics, class III - maintenance of sinus rhythm',
    'Droperidol' : 'antipsychotics, first generation - prevention of post operative nausea and vomiting',
    'Dulaglutide' : 'GLP1 receptor agonist - T2DM',
    'Duloxetine' : 'SNRI - depression, generalised anxiety disorder, diabetic neuropathy, urinary incontinence',
    'Dupilumab' : 'DMARD - interleukin inhibitors - atopic eczema, severe asthma',
    'Durvalumab' : 'anti-PD-L1 monoclonal antibody - non-small cell lung cancer',
    'Dutasteride' : '5alpha reductase inhibitors - BPH',
    'Eculizumab' : 'DMARD - monoclonal antibody - paroxysmal nocturnal haemoflobinuria, myasthenia gravis',
    'Edoxaban' : 'direct factor Xa inhibitor - DVT/PE treatment and prophylaxis, embolism prophylaxis in AF',
    'Efavirenz' : 'antiretroviral - HIV infection',
    'Eflornithine' : 'antiprotozoals - facial hirsutism',
    'Eletriptan' : 'triptans - migraine',
    'Eliglustat' : 'glucosylceramide synthase inhibitors - gauchers disease',
    'Elotuzumab' : 'anti-lymphocyte monoclonal antibodies - multiple myeloma',
    'Eltrombopag' : 'thrombopoietin receptor agonist - chronic immune thrombocytopenic purpura',
    'Elvitegravir' : 'antiretroviral - HIV infection',
    'Emicizumab' : 'DMARD - monoclonal antibody - prophylaxis of haemorrhage in haemophilia A ',
    'Empagliflozin' : 'SGLT2 inhibitors - T2DM, heart falure',
    'Emtricitabine' : 'antiretroviral - HIV infection',
    'Enalapril' : 'ACEi - hypertension, heart failure',
    'Encorafenib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma (BRAF +ve)',
    'Enfuvirtide' : 'antiretroviral - HIV infection',
    'Enoximone' : 'PDE3 inhibitor - CHF with reduced CO',
    'Entacapone' : 'catechol-o-methyltransferase inhibitors - Parkinsons disease',
    'Entecavir' : 'antivirals - nucleoside analogues - chronic hepatitis B',
    'Enzalutamide' : 'androgen receptor inhibitors - prostate cancer',
    'Eplerenone' : 'mineralocorticoid receptor antagonists - heart failure with reduced ejection fraction',
    'epoetin' : 'epoetins - anaemia in chronic renal failure',
    'Epoprostenol' : 'prostaglandins and analogues - primary pulmonary hypertension, inhibition of platelet aggregation during dialysis',
    'Eprosartan' : 'ARB - hypertension',
    'Eptinezumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'Eravacycline' : 'tetracyclines - complicated intra-abdominnal infections',
    'Erdosteine' : 'mucolytics - bronchitis exacerbation',
    'Erenumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'Ergocalciferol' : 'vitamins and analogues - vitamin D deficiency, hypocalcaemia of hypoparathyroidism',
    'Eribulin' : 'antineoplastics, other - metastatic breast cancer',
    'Erlotinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer, metastatic pancreatic cancer',
    'Ertapenem' : 'carbapenem antibiotics - abdominal infections, gynaecological infections, community acquired pneumonia, diabetic foot infections',
    'Ertugliflozin' : 'SGLT2 inhibitors - T2DM',
    'Erythromycin' : 'macrolide antibiotics - susceptible infections (e.g. legionella, campylobacter, skin) in penicillin hypersensitivity, impetigo, cellulitis, community acquired pneumonia, early syphilis, chlamydia, prostatisis, pertussis, acne, rosacea',
    'Escitalopram' : 'SSRIs - depression, anxiety disorders, panic disorder, OCD',
    'Esketamine' : 'NMDA receptor blocker - anaesthesia, emergency analgesia, major depressive disorder',
    'Esomeprazole' : 'PPI - PUD, prophylaxis of NSAID associated ulcers, GORD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'Estradiol' : 'oestrogens - vaginal atrophy in post-menopausal women, prophylaxis of recurrent UTI in post-menopausal women',
    'Estriol' : 'oestrogens - vaginal atrophy in post-menopausal women, prophylaxis of recurrent UTI in post-menopausal women',
    'Etanercept' : 'DMARD - TNF-a inhibitor - RA, psoriatic arthritis, AS, plaque psoriasis',
    'Etelcalcetide' : 'Bone resorption inhibitors - secondary hyperparathyroidism',
    'Ethosuximide' : 'antiepileptics - absence seizures, myoclonic seizures',
    'Etodolac' : 'NSAID - pain in RA and OA',
    'Etomidate' : 'IV anaesthetics - induction of anaesthesia',
    'Etonogestrel' : 'progestogens - contraception',
    'Etoposide' : 'chemotherapy - cytotoxic drugs - small cell carcinoma of bronchus, lymphomas, testicular cancer',
    'Etoricoxib' : 'NSAID - pain and inflammation in RA, OA and AS, acute gout',
    'Etravirine' : 'antiretroviral - HIV infection',
    'Everolimus' : 'chemotherapy - protein kinase inhibitor - neuroendocrine tumours (pancreatic or gastro-intestinal origin)',
    'Evolocumab' : 'lipid modifying drugs - hyperlipidaemia, homozygous familial hypercholesterolaemia',
    'Exemestane' : 'aromatase inhibitors - adjuvant in oestrogen-receptor positive breast cancer',
    'Exenatide' : 'GLP1 receptor agonist - T2DM',
    'Ezetimibe' : 'cholesterol abbsorption inhibitors - adjunct in hyperlipidaemia',
    'Famciclovir' : 'antivirals - nucleoside analogues - HSV, HZV infection',
    'Famotidine' : 'H2 receptor antagonists - gastroduodenal ulceration, reflux oesophagitis',
    'Fampridine' : 'cholinergic receptor stimulators - MS',
    'Faricimab' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, ',
    'Febuxostat' : 'xanthine oxidase inhibitors - chronic hyperuricaemia in gout, acute hyperuricaemia in haematologic malignancies',
    'Fedratinib' : 'chemotherapy - protein kinase inhibitor - splenomegaly',
    'Felbinac' : 'NSAID - pain in knee or hand osteoarthritis',
    'Felodipine' : 'calcium channel blockers - angina, hypertension',
    'Fenfluramine' : 'antiepileptics - seizures in Dravet syndrome',
    'Fenofibrate' : 'fibrates - adjunct in hyperlipidaemia',
    'Fentanyl' : 'opioids - severe pain, analgesia and anaesthesia during operation',
    'Fidaxomicin' : 'macrocyclic antibiotic - C diff infection',
    'Filgotinib' : 'DMARD - JAK1 inhibitor - RA, ulcerative colitis',
    'Filgrastim' : 'granulocute colony stimulating factors - neutropenia',
    'Finasteride' : '5alpha reductase inhibitors - BPH, androgenic alopecia',
    'Finerenone' : 'mineralocorticoid receptor antagonists - CKD',
    'Fingolimod' : 'sphingosine-1-phosphate receptor modulator - MS',
    'flecainide' : 'antiarrhythmics, class Ic - supraventricular arrhythmias, ventricular arrhythmias',
    'Flucloxacillin' : 'penicillin antibiotics - betalacatmase producing staph infections, impetigo, cellulitis, diabetic foot infection, endocarditis',
    'Fluconazole' : 'antifungals - candidiasis, balanitis, tinea infection, invasive candidal infection, prevention of fungal infections in immunocompromised patients',
    'Flumazenil' : 'antidotes - reversal of sedative effects of benzodiazepines',
    'Fluocinonide' : 'corticosteroids - severe eczema, psoriasis',
    'Fluorouracil' : 'chemotherapy - antimetabolites - skin cancer, GI tract tumours, breast cancers, colorectal cancer',
    'Fluoxetine' : 'SSRIs - major depression, bulimia nervosa, OCD disorder',
    'Flupentixol' : 'antipsychotics, first generation - schizophrenia, depressive illness',
    'Flurazepam' : 'benzodiazepines - insomnia',
    'Flurbiprofen' : 'NSAID - pain, inhibition of intra-operative miosis',
    'Flutamide' : 'androgen receptor inhibitors - prostate cancer',
    'Fluticasone' : 'corticosteroids - asthma, allergic rhinitis, nasal polyps, psoriasis, severe inflammatory skin disorders',
    'Fluvastatin' : 'HMG-CoA reductase inhibitor - hyperlipidaemia',
    'Follitropin' : 'gonadotrophins - infertility',
    'Formaldehyde' : 'aldehydes and derivatives - warts',
    'formoterol' : 'long acting beta agonists - COPD, asthma',
    'Fosfomycin' : 'phosphonic acid antibiotic - UTI, osteomyelitis, meningitis',
    'Fostemsavir' : 'antiretroviral - HIV infection',
    'Fremanezumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'Frovatriptan' : 'triptans - migraine',
    'Fulvestrant' : 'anti-oestrogens - oestrogen receptor positive breast cancer',
    'Furosemide' : 'loop diuretic - oedema, hypertension',
    'Gabapentin' : 'antiepileptics - focal seizures, neuropathic pain, MS',
    'Galantamine' : 'acetylcholinesterase inhibitor - Alzheimers disease',
    'Galcanezumab' : 'DMARD - monoclonal antibody - migraine prophylaxis',
    'Ganciclovir' : 'antivirals - nucleoside analogues - CMV infection, acure herpetic keratits',
    'Ganirelix' : 'anti-gonadotrophin releasing hormones - infertility',
    'Gefitinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'Gemcitabine' : 'chemotherapy - antimetabolites - non-small cell lung cancer, pancreatic cancer, bladder cancer, ovarian cancer, breast cancer',
    'Gemeprost' : 'prostaglandins and analogues - termination of pregnancy',
    'Gemfibrozil' : 'fibrates - hyperlipidaemia',
    'Gentamicin' : 'aminoglycoside antibiotics - gram positive or HACEK endocarditis, eye infections, diabetic foot infections, diverticulitis, meningitis, pneumonia, prostatitis, CNS infections, pyelonephritis',
    'Gilteritinib' : 'chemotherapy - protein kinase inhibitor - AML',
    'Givosiran' : 'interfering RNA - acute hepatic porphyria',
    'Glasdegib' : 'antineoplastics, other - AML',
    'Gliclazide' : 'sulfonylureas - T2DM',
    'Glimepiride' : 'sulfonylureas - T2DM',
    'Glipizide' : 'sulfonylureas - T2DM',
    'Glucagon' : 'glycogenolytic hormones - diabetic hypoglycaemia, beta blocker overdose',
    'Glucosamine' : 'natural substance - osteoarthritis of the knee',
    'Glucose' : 'natural substance - hypoglycaemia, DKA',
    'Glutaraldehyde' : 'aldehydes and derivatives - warts',
    'Glycerol' : 'stimulant laxatives - constipation',
    'Golimumab' : 'DMARD - TNF-a inhibitor - RA, psoriatic arthritis, AS, ulcerative colitis',
    'Gonadorelin' : 'gonadotrophin releasing hormones - assessment of pituitary function',
    'Goserelin' : 'gonadotrophin releasing hormones - prostate cancer',
    'Granisetron' : 'serotonin receptor antagonists - nausea and vomiting',
    'Griseofulvin' : 'antifungals - tinea pedis, dermatophyte infection',
    'Guanfacine' : 'alpha-adrenoreceptor agonists - ADHD',
    'Guselkumab' : 'DMARD - interleukin inhibitors - plaque psoriasis, psoriatic arthritis',
    'Haloperidol' : 'antipsychotics, first generation - post-op nausea and vomiting, nausea and vomiting and restlessness in palliative care, schizophrenia, acute delirium, mania, agitation, severe tic disorders, chorea',
    'Heparin' : 'heparins - PE/DVT, thromboprophylaxis, haemodialysis, unstable angina, acute peripheral arterial occlusion',
    'Hydrocortisone' : 'corticosteroids - thyrotoxic crisis, adrenocortical insufficiency, anaphylaxis, corticosteroid replacement, Addisons disease, adrenal crisis, angioedema, severe IBD, acute asthma, inflammatory skin disorders',
    'Hypromellose' : 'ocular lubricants - dry eyes',
    'Ibrutinib' : 'chemotherapy - protein kinase inhibitor - mantle cell lymphoma, CLL, waldenstroms macroglobulinaemia',
    'Ibuprofen' : 'NSAID - pain, migraine, inflammation, pyrexia',
    'Ichthammol' : 'anti-infectives - chronic lichenified eczema',
    'Idarucizumab' : 'antidotes - dabigatran reversal',
    'Idebenone' : 'nootropics - lebers hereditary optic neuropathy',
    'Idelalisib' : 'chemotherapy - protein kinase inhibitor - CLL, follicular lymphomma',
    'Idursulfase' : 'enzymes - mucopolysaccharidosis',
    'Ifosfamide' : 'chemotherapy - alkylating agents - malignant disease',
    'Iloprost' : 'prostaglandins and analogues - pulmonary hypertension, raynauds disease, lower limb ischaemia',
    'Imatinib' : 'chemotherapy - protein kinase inhibitor - CML, ALL, gastro-intestinal stromal tumours, myelodysplasia',
    'Imiglucerase' : 'enzymes - gauchers disease',
    'Imiquimod' : 'topical preparations - warts, actinic keratosis',
    'Inclisiran' : 'lipid modifying drugs - hyperlipidaemia, homozygous familial hypercholesterolaemia',
    'Indacaterol' : 'long acting beta agonists - COPD',
    'Indapamide' : 'thiazide like diuretics - hypertension',
    'Indometacin' : 'NSAID - pain and inflammation in RA, OA and AS, dysmenorrhoea, acute gout',
    'Indoramin' : 'alpha-adrenoreceptor blockers - hypertension, BPH',
    'Infliximab' : 'DMARD - TNF-a inhibitor - RA, psoriatic arthritis, AS, plaque psoriasis, crohns disease, ulcerative colitis',
    'Insulin' : 'hormones and analogues - diabetes mellitus',
    'Ipilimumab' : 'chemotherapy - monoclonal antibodies - melanoma, renal cell carcinoma, non-small cell lung cancer, mesothelioma, colorectal cancer',
    'Ipratropium' : 'antimuscarinics - bronchospasm, acute asthma',
    'Irbesartan' : 'ARB - hypertension, renal disease',
    'Iron' : 'vitamins and analogues - iron deficient anaemia',
    'Isatuximab' : 'chemotherapy - monoclonal antibodies - multiple myeloma',
    'Isavuconazole' : 'antifungals - invasive aspergillosis',
    'Isocarboxazid' : 'MAO inhibitors - depression',
    'Isoflurane' : 'volatile liquid anaesthetics - anaesthesia',
    'Isoniazid' : 'antimycobacterials - TB',
    'Isotretinoin' : 'retinoids - acne vulgaris',
    'Itraconazole' : 'antifungals - candidiasis, pityriasis versicolor, tinea infections, aspergillosis, crytococcosis',
    'Ivabradine' : 'negative inotropes - angina, heart failure',
    'Ivacaftor' : 'mucolytics - cystic fibrosis',
    'Ivermectin' : 'antihelmintics - rosacea, scabes, onchocerciasis',
    'Ixazomib' : 'chemotherapy - proteasome inhibitors - multiple myeloma',
    'Ixekizumab' : 'DMARD - interleukin inhibitors - plaque psoriasis, psoriatic arthritis, spondyloarthritis',
    'Kaolin' : 'antipropulsives - acute diarrhoea',
    'Ketamine' : 'NMDA receptor blocker - anaesthesia, pain in palliative care, emergency analgesia',
    'Ketoconazole' : 'antifungals - fungal skin infections, seborrhoeic dermatitis, pityriasis versicolor, candidiasis',
    'Ketoprofen' : 'NSAID - pain and inflammation in RA, OA and AS, dysmenorrhoea, acute gout',
    'Ketorolac' : 'NSAID - acute post-op pain and inflammation',
    'Ketotifen' : 'sedating antihistamines - allergic reactions',
    'labetalol' : 'alpha and beta blockers - anaesthesia, hypertension, pre-eclampsia',
    'Lacidipine' : 'calcium channel blockers - hypertension',
    'Lacosamide' : 'antiepileptics - focal seizures, tonic-clonic seizures',
    'Lactulose' : 'osmotic laxatives - constipation, hepatic encephalopathy',
    'Lamivudine' : 'antiretroviral - HIV',
    'Lamotrigine' : 'antiepileptics - focal seizures, tonic-clonic seizures, seizures in lennox-gastaut syndrome, bipolar disorder',
    'Lanadelumab' : 'DMARD - monoclonal antibody - hereditary angioedema',
    'Lanreotide' : 'somatostatin analogues - acromegaly, neuroendocrine tumours',
    'Lansoprazole' : 'PPI - PUD, prophylaxis of NSAID associated ulcers, GORD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'Lanthanum' : 'phosphate binders - hyperphosphataemia',
    'Lapatinib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'Laronidase' : 'enzymes - mucopolysaccharidosis',
    'Latanoprost' : 'prostaglandins and analogues - ocular hypertension, chronic glaucoma',
    'Leflunomide' : 'DMARD - other - RA, psoriatic arthritis, AS',
    'Lenalidomide' : 'chemotherapy - thalidomides - multiple myeloma, myelodysplasia, mantle cell lymphoma, follicular lymphoma',
    'Lenograstim' : 'granulocute colony stimulating factors - neutropenia',
    'Lenvatinib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma',
    'Letermovir' : 'antivirals - other - CMV infection and prophylaxis',
    'Letrozole' : 'aromatase inhibitors - oestrogen-receptor positive breast cancer',
    'Levamisole' : 'antihelmintics - roundworm infections',
    'Levetiracetam' : 'antiepileptics - focal seizures, tonic-clonic seizures, myoclonic seizures, status epilepticus',
    'Levocarnitine' : 'amino acids and derivatives - carnitine deficiency',
    'Levofloxacin' : 'quinolone antibiotics - eye infections, COPD exacerbation, URI, H pylori, pneumonia',
    'Carbidopa' : 'dopamine precursors - Parkinsons disease',
    'Levodopa' : 'dopamine precursors - Parkinsons disease',
    'Levomenthol' : 'antipruritics - pruritus',
    'Levonorgestrel' : 'progestogens - contraception',
    'lidocaine' : 'local anaesthetics - CPR, ventricular arrhythmias, anaesthesia, pain relief',
    'Linaclotide' : 'guanylate cyclase agonist - IBS with constipation',
    'Linagliptin' : 'DPP4 inhibitors - T2DM',
    'Linezolid' : 'oxazolidinone antibiotic - pneumonia, complicated skin and soft tissue infections',
    'Liraglutide' : 'GLP1 receptor agonist - T2DM',
    'Lisinopril' : 'ACEi - hypertension, heart failure, renal failure',
    'lithium' : 'antipsychotics, other - bipolar disorder, mania, recurrent depression',
    'Lixisenatide' : 'GLP1 receptor agonist - T2DM',
    'Lodoxamide' : 'mast cell stabilisers - allergic conjunctivitis',
    'Lofepramine' : 'tricyclic antidepressants - depression',
    'Lomitapide' : 'lipid modifying drugs - hyperlipidaemia, homozygous familial hypercholesterolaemia',
    'Lomustine' : 'chemotherapy - alkylating agents - hodgkins disease, melanoma',
    'loperamide' : 'antipropulsives - diarrhoea, faecal incontinence, bowel colic in palliative care',
    'Loprazolam' : 'benzodiazepines - insomnia',
    'Loratadine' : 'non-sedating antihistamine - allergic reactions',
    'Lorazepam' : 'benzodiazepines - anxiety, insomnia, panic attacks, sedation,status epilepticus',
    'Lorlatinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with ALK mutations',
    'Lormetazepam' : 'benzodiazepines - insomnia',
    'Losartan' : 'ARB - hypertension, heart failure, diabetic nephropathy',
    'Loxapine' : 'antipsychotics, first generation - agitation in schizophrenia or bipolar disorder',
    'Lusutrombopag' : 'thrombopoietin receptor agonist - thrombocytopenia in chronic liver disease',
    'Lutropin' : 'gonadotrophins - infertility',
    'Lymecycline' : 'tetracyclines - acne vulgaris, chlamydia, rickettsia, mycoplasma',
    'Macitentan' : 'endothelin receptor antagonists - pulmonary hypertension',
    'Malathion' : 'parasiticides - lice, scabies',
    'Mannitol' : 'mucolytics, osmotic laxatives - cerebral oedema, raised intraocular pressure, cystic fibrosis',
    'Maraviroc' : 'antivirals - other - HIV infection',
    'Mebendazole' : 'antihelmintics - threadworm, hookworm, roundworm infections',
    'Mebeverine' : 'antispasmodics - gastrointestinal spasm, IBS',
    'Mefloquine' : 'antimalarials - malaria treatment and prophylaxis',
    'Melatonin' : 'non-benzodiazepine sedatives and hypnotics - insomnia, jet lag',
    'Meloxicam' : 'NSAID - pain and inflammation in RA, OA and AS',
    'Melphalan' : 'chemotherapy - alkylating agents - multiple myeloma, polycythaemia vera, malignant melanoma, soft tissue sarcoma',
    'memantine' : 'NMDA receptor blocker - Alzheimers disease',
    'Menotrophin' : 'gonadotrophins - infertility',
    'Mepolizumab' : 'DMARD - monoclonal antibody - eosinophilic asthma',
    'Meptazinol' : 'opioids - pain',
    'Metformin' : 'biguanides - T2DM, PCOS',
    'Mercaptopurine' : 'DMARD - antimetabolites, chemotherapy - antimetabolites - crohns disease, ulcerative colitis, ALL, AML, CML',
    'Meropenem' : 'carbapenem antibiotics - servere bacterial infections ',
    'Mesalazine' : 'aminosalicylates - acute ulcerative colitis, maintenance of remission of ulcerative colitis',
    'Mesna' : 'antidotes - cytotoxic induced urothelial toxicity',
    'Metaraminol' : 'sympathomimetics - acute hypotension',
    'methadone' : 'opioids - pain, opioid dependence',
    'Methocarbamol' : 'muscle relaxants - muscle spasm',
    'Methotrexate' : 'DMARD - antimetabolites - crohns disease, RA, neoplastic diseases, psoriasis',
    'Methoxyflurane' : 'volatile liquid anaesthetics - pain',
    'Methyldopa' : 'antihypertensive, centrally acting - hypertension',
    'Metoclopramide' : 'dopamine receptor antagonists - nausea and vomiting, hiccup in palliative care, acute migraine',
    'Metolazone' : 'thiazide like diuretics - oedema, hypertension',
    'Metreleptin' : 'hormones and analogues - leptin deficiency in lipodystrophy',
    'Metronidazole' : 'antibiotics, other - anaerobic bacterial infections',
    'Metyrapone' : 'enzyme inhibitors - cushings syndrome, resistant oedema',
    'Mexiletine' : 'sodium channel blockers - ventricular arrhythmias',
    'Micafungin' : 'antifungals - candidiasis',
    'Miconazole' : 'antifungals - fungal skin infections, candidiasis',
    'Midazolam' : 'benzodiazepines - status epilepticus, sedation, restlessness in palliative care',
    'Midostaurin' : 'chemotherapy - protein kinase inhibitor - AML, mastocytosis, mast cell leukaemia',
    'Mifamurtide' : 'immunostimulants - osteosarcoma',
    'Mifepristone' : 'progesterone receptor modulators - termination of pregnancy',
    'Migalastat' : '?? - fabrys disease',
    'Miglustat' : 'glucosylceramide synthase inhibitors - gauchers disease, niemann-pick disease',
    'Milrinone' : 'PDE3 inhibitor - acute heart failure',
    'Minocycline' : 'tetracyclines - acne vulgaris, chlamydia, rickettsia, mycoplasma',
    'Minoxidil' : 'potassium channel openers - severe hypertension',
    'Mirabegron' : 'beta 3 agonists - urinary frequency, urgency and incontinence',
    'Mirtazapine' : 'tetracyclic antidepressants - major depression',
    'Misoprostol' : 'prostaglandins and analogues - termination of pregnancy',
    'Mitomycin' : 'chemotherapy - cytotixc antibiotics - bladder tumours, gastrointestinal cancer, breast cancer, non-small cell lung cancer, pancreatic cancer',
    'Mitotane' : 'antineoplastics, other - adrenocortical carcinoma',
    'Mitoxantrone' : 'chemotherapy - anthracyclines - metastatic breast cancer, non-hodgkins lymphoma, hepatocellular carcinoma',
    'Mivacurium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'Mizolastine' : 'non-sedating antihistamine - allergic reactions',
    'Mobocertinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with EGFR mutations',
    'Moclobemide' : 'MAO inhibitors - depression, social anxiety disorder',
    'Modafinil' : 'sympathomimetics - excessive sleepiness in narcolepsy',
    'Mogamulizumab' : 'chemotherapy - monoclonal antibodies - mycosis fungiodes, sezary syndrome',
    'Molnupiravir' : 'antivirals - other - COVID 19',
    'mometasone' : 'corticosteroids - asthma prophylaxis, psoriasis, inflammatory skin disorders',
    'Montelukast' : 'leukotriene receptor antagonist - asthma prophylaxis',
    'Morphine' : 'opioids - pain, MI, acute pulmonary oedema, breathlessness in palliative care',
    'Moxifloxacin' : 'quinolone antibiotics - local infections, sinusitis, community acquired pneumonia, bronchitis exacerbation, pelvic inflammatory disease, complicated skin and soft tissue infections',
    'Moxisylyte' : 'peripheral vasodilators - raynauds syndrome',
    'Moxonidine' : 'antihypertensive, centrally acting - hypertension',
    'Mupirocin' : 'antibiotics, other - gram positive bacterial skin infections, non-bullous impetigo',
    'Nabilone' : 'cannabinoids - nausea and vomiting caused by cytotoxic chemotherapy',
    'Nabumetone' : 'NSAID - pain and inflammation in OA and RA',
    'Nadolol' : 'beta blocker - hypertension, angina, arrhythmias, migraine prophylaxis, thyrotoxicosis',
    'Nafarelin' : 'gonadotrophin releasing hormones - endometriosis, IVF',
    'Naldemedine' : 'opioid receptor antagonists - opioid induced constipation',
    'Nalmefene' : 'opioid receptor antagonists - reduction of alcohol consumption in alcohol dependence',
    'Naloxegol' : 'opioid receptor antagonists - opioid induced constipation',
    'naloxone' : 'antidotes, opioid receptor antagonists - opioid overdose',
    'naltrexone' : 'opioid receptor antagonists - relapse prevention in opioid and alcohol dependence',
    'Neomycin' : 'aminoglycoside antibiotics - bacterial skin infections, hepatic coma',
    'Naproxen' : 'NSAID - pain and inflammation in rheumatoid conditions, acute gout, acute migraine, dysmenorrhoea',
    'Naratriptan' : 'triptans - acute migraine',
    'Natalizumab' : 'anti-lymphocyte monoclonal antibodies - relapsing remitting MS',
    'Nebivolol' : 'beta blocker - hypertension, heart failure',
    'Nelarabine' : 'chemotherapy - antimetabolites - T-cell ALL and T-cell lymphoblastic lymphoma',
    'Neostigmine' : 'acetylcholinesterase inhibitor - myasthenia gravis, reversal of non-depolarising neuromuscular blockade',
    'Nepafenac' : 'NSAID - post operative pain',
    'Neratinib' : 'chemotherapy - protein kinase inhibitor - breast cancer (HER2 +ve)',
    'Netilmicin' : 'aminoglycoside antibiotics - local infections',
    'Nevirapine' : 'antiretroviral - HIV infection',
    'Nicorandil' : 'potassium channel openers - angina',
    'Nicotinamide' : 'vitamins and analogues - inflammatory acne vulgaris',
    'Nicotine' : 'nicotinic receptor agonists - smoking cessation aid',
    'Nifedipine' : 'calcium channel blockers - raynauds syndrome, premature labour, hiccup in palliative care, chronic anal fissure',
    'Nilotinib' : 'chemotherapy - protein kinase inhibitor - CML (philadelphia chromosome positive)',
    'Nimodipine' : 'calcium channel blockers - prevention and treatment of ischaemic neurological defects following aneurysmal subarachnoid haemorrhage',
    'Nintedanib' : 'chemotherapy - protein kinase inhibitor - ideopathic pulmonary fibrosis, chronic fibrosing interstitial lung disease, systemic sclerosis associated interstitial lung disease',
    'Niraparib' : 'antineoplastics, other - ovarian cancer, peritoneal cancer',
    'Nitrazepam' : 'benzodiazepines - insomnia',
    'Nitrofurantoin' : 'antibiotics, other - LUTI',
    'Nivolumab' : 'anti-PD1 monoclonal antibody - melanoma, renal cell carcinoma, non-small cell lung cancer, mesothelioma, SCC, hodgkin lympoma',
    'Nizatidine' : 'H2 receptor antagonists - GORD, peptic ulcer',
    'Nonoxinol' : 'spermicidal agents - contraception',
    'Norethisterone' : 'progestogens - endometriosis, menorrhagia, dysmenorrhoea, contraception, breast cancer',
    'Nortriptyline' : 'tricyclic antidepressants - depression, neuropathic pain',
    'Nusinersen' : 'drugs for neuromuscular disorders - 5q spinal muscular atrophy',
    'Nystatin' : 'antifungals - oral candidiasis, oral fungal infections',
    'Obinutuzumab' : 'anti-lymphocyte monoclonal antibodies - CLL, follicular lymphomma',
    'Ocrelizumab' : 'anti-lymphocyte monoclonal antibodies - MS',
    'Octreotide' : 'somatostatin analogues - carcinoid syndrome, acromegaly, neuroendocrine tumours, intestinal secretions and vomiting due to bowel obstruction in palliative care',
    'Odevixibat' : 'ileal bile acid transporter inhibitor - progressive familial intrahepatic cholestasis',
    'Ofatumumab' : 'anti-lymphocyte monoclonal antibodies - MS',
    'Ofloxacin' : 'quinolone antibiotics - local infections, UTI, LRTI, prostatitis, complicated skin infections, uncomplicated gonorrhoea, PID, chalmydia',
    'Olanzapine' : 'antipsychotics, second generation - schizophrenia, mania, bipolar disorder',
    'Olaparib' : 'antineoplastics, other - ovarian cancer, peritoneal cancer',
    'Olmesartan' : 'ARB - hypertension, heart failure',
    'Olodaterol' : 'long acting beta agonists - COPD',
    'Olopatadine' : 'antihistamines - allergic conjunctivitis',
    'Omalizumab' : 'DMARD - monoclonal antibody - allergic asthma, chronic spontaneous urticaria',
    'Omeprazole' : 'PPI - dispepsia, PUD, prophylaxis of NSAID associated ulcers, GORD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'Ondansetron' : 'serotonin receptor antagonists - nausea and vomiting',
    'Opicapone' : 'catechol-o-methyltransferase inhibitors - Parkinsons disease',
    'Opium' : 'opioid - acute diarrhoea',
    'Oritavancin' : 'glycopeptide antibiotics - acute bacterial skin and skin structure infections',
    'Orlistat' : 'antiobesity drugs - obesity',
    'Oseltamivir' : 'antivirals - neuraminidase inhibitors - prevention and treatment of influenza',
    'Osilodrostat' : 'enzyme inhibitors - cushings syndrome',
    'Osimertinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer',
    'Ospemifene' : 'oestrogen receptor modulator - vaginal atrophy in post-menopausal women',
    'Oxaliplatin' : 'chemotherapy - platinum compounds - metastatic colorectal cancer',
    'Oxazepam' : 'benzodiazepines - anxiety, insomnia',
    'Oxcarbazepine' : 'antiepileptics - focal seizures, tonic-clonic seizures',
    'oxerutins' : '?? - oedema associated with chronic venous insufficiency',
    'oxybutynin' : 'antimuscarinics - urinary frequency, urgency and incontinence',
    'oxycodone' : 'opioids - pain',
    'Oxymetholone' : 'anabolic steroids - aplastic anaemia',
    'Oxytocin' : 'oxytocin and analogues - induction of labour, caesarean section, postpartum haemorrhage',
    'Ozanimod' : 'Immunomodulating drugs - MS',
    'Paclitaxel' : 'chemotherapy - taxanes - ovarian cancer, breast cancer, Kaposis sarcoma',
    'Palbociclib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'Paliperidone' : 'antipsychotics, second generation - schizophrenia, schizoaffective disorder',
    'Palivizumab' : 'monoclonal antibodies - prevention of serious RSV infection in children',
    'Palonosetron' : 'serotonin receptor antagonists - nausea and vomiting after chemotherapy',
    'Pancreatin' : 'enzymes - pancreatic insufficiency',
    'Pancuronium' : 'non-depolarising neuromuscular blockers - neuromuscular blockade during surgery and intubation',
    'Panitumumab' : 'chemotherapy - monoclonal antibodies - colorectal cancer',
    'Panobinostat' : 'antineoplastics, other - multiple myeloma',
    'Pantoprazole' : 'PPI - PUD, prophylaxis of NSAID associated ulcers, GORD, oesophagitis, zollinger-ellison syndrome, H pylori',
    'Paracetamol' : 'analgesics, non-opiod - pain, pyrexia',
    'Parecoxib' : 'NSAID - post operative pain',
    'Paricalcitol' : 'vitamins and analogues - secondary hyperparathyroidism',
    'Paroxetine' : 'SSRIs - depression, panic disorder, OCD, PTSD, generalised anxiety disorder',
    'Pasireotide' : 'somatostatin analogues - Cushings disease, acromegaly',
    'Patisiran' : 'neuroprotective drugs - polyneurpathy',
    'Pazopanib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, soft tissue sarcomas',
    'Pegaspargase' : 'antineoplastics, other - ALL',
    'Pegcetacoplan' : 'Immunomodulating drugs - paroxysmal nocturnal haemoflobinuria',
    'Pegfilgrastim' : 'granulocute colony stimulating factors - neutropenia',
    'Pegvisomant' : 'hormones and analogues - acromegaly',
    'Pembrolizumab' : 'anti-PD1 monoclonal antibody - melanoma, renal cell carcinoma,urothelial carcinoma,  non-small cell lung cancer, mesothelioma, SCC, hodgkin lympoma, oesophageal carcinoma, breast cancer, cervical cancer, endometrial cancer, biliary cancer',
    'Pemetrexed' : 'chemotherapy - antimetabolites - mesothelioma, non-small cell lung cancer',
    'Pemigatinib' : 'chemotherapy - protein kinase inhibitor - cholangiocarcinoma with FGFR2 fusion',
    'Penicillamine' : 'antidotes and chelating agents - wilsons disease, severe active RA, autoimmmune hepatitis, cystinuria',
    'Pentazocine' : 'opioids - pain',
    'Pentostatin' : 'chemotherapy - cytotixc antibiotics - hairy cell leukaemia',
    'Pentoxifylline' : 'peripheral vasodilators - PVD, venous leg ulcer',
    'Perampanel' : 'antiepileptics - focal seizures, tonic-clonic seizures',
    'Pericyazine' : 'antipsychotics, first generation - schizophrenia, psychoses, severe anxiety, agitation',
    'Permethrin' : 'parasiticides - scabies, lice',
    'Pertuzumab' : 'chemotherapy - monoclonal antibodies - breast cancer (HER2 +ve)',
    'Phenelzine' : 'MAO inhibitors - depression',
    'Phenindione' : 'vitamin K antagonists - prophylaxis of embolisation in AF, prosthetic heart valves',
    'Phenobarbital' : 'barbituates - status epilepticus, all forms of epilepsy except typical absense seizures',
    'Phenol' : 'sclerosants - haemmorrhoids',
    'Phenytoin' : 'antiepileptics - focal seizures, tonic-clonic seizures, status epilepticus, seizures associated with head trauma or neurosurgery',
    'Pholcodine' : 'cough suppressants - dry cough',
    'Phosphate' : 'vitamins and analogues - hypophosphatemia',
    'Phytomenadione' : 'antidotes and chelating agents - INR>8.0 or bleeding in patients on warfarin, reversal of anticoagulation',
    'Pilocarpine' : 'parasympathomimetics - glaucoma, zerostomia, Sjogrens syndrome',
    'Pimecrolimus' : 'calcineurin inhibitors - atopic eczema, psoriasis',
    'Pimozide' : 'antipsychotics, first generation - schizophrenia, psychosis',
    'Pindolol' : 'beta blocker - hypertension, angina',
    'Pioglitazone' : 'thiazolidinedione - T2DM',
    'Piracetam' : 'CNS stimulants - cortical myoclonus',
    'Pirfenidone' : '?? unknown - idiopathic pulmonary fibrosis',
    'Piroxicam' : 'NSAID - pain and inflammation in RA, OA and AS',
    'Pitolisant' : 'CNS stimulants - narcolepsy',
    'Pixantrone' : 'chemotherapy - anthracyclines - non-hodgkins B cell lymphomas',
    'Pizotifen' : 'sedating antihistamines - migraine prophylaxis, cluster headache prophylaxis',
    'Pomalidomide' : 'chemotherapy - thalidomides - multiple myeloma',
    'Ponatinib' : 'chemotherapy - protein kinase inhibitor - CML, ALL  (philidelphia chromosome +vs)',
    'Ponesimod' : 'Immunomodulating drugs - MS',
    'pralidoxime' : 'antidotes and chelating agents - adjunct in organophsphate poisoning',
    'Pralsetinib' : 'chemotherapy - protein kinase inhibitor - non-small cell lung cancer with RET fusion',
    'Pramipexole' : 'dopamine receptor agonists - Parkinsons disease, restless legs syndrome',
    'Prasterone' : 'oestrogens - vaginal atrophy in post-menopausal women',
    'Prasugrel' : 'antiplatelet drugs - prevention of atherothrombotic events',
    'Praziquantel' : 'antihelmintics - tapeworm infections, schistosoma infections',
    'Prazosin' : 'alpha-adrenoreceptor blockers - hypertension, raynauds syndrome, BPH',
    'Prednisolone' : 'corticosteroids - COPD, ARDS, asthma, suppression of inflammatory and allergic disorders, idiopathic thrombocytopenic purpura, eczema, IBD, myasthenia gravis, polymmyalgia rheymatica, vasculitis, SLE, polymyositis, anorexia in palliative care, proctitis',
    'Pregabalin' : 'antiepileptics - focal seizures, neuropathic pain, generalised anxiety disorder',
    'Pridinol' : 'muscle relaxants - muscle spasm',
    'Primaquine' : 'antimalarials - malaria treatment',
    'Primidone' : 'barbituates - all epilespty except typical absence seizures, essential tremor',
    'Procarbazine' : 'antineoplastics, other - hodgkins lumphoma',
    'Proflavine' : 'antiseptics - infected wounds',
    'Progesterone' : 'progestogens - contraception, HRT, IVF, threatened miscarriage',
    'promazine' : 'antipsychotics, first generation - agitation and restlessness in elderly',
    'promethazine' : 'sedating antihistamines - allergic reactions, anaphylaxis, sedation',
    'Propofol' : 'IV anaesthetics - induction of anaesthesia, sedation, maintenance of anaesthesia',
    'propanolol' : 'beta blocker - thyrotoxicosis, hypertension, prophylaxis of variceal bleeding, phaechromocytoma, angina, hypertrophic cardiomyopathy, anxiety tachycardia, essential tremor, migraine prophylaxis, arrhythmias',
    'pyridostigmine' : 'acetylcholinesterase inhibitor - myasthenia gravis',
    'Prucalopride' : 'prokinetic agents - chronic constipation',
    'Pyrazinamide' : 'antimycobacterials - TB',
    'Pyrimethamine' : 'antiprotozoals - toxoplasmosis in pregnancy',
    'Quetiapine' : 'antipsychotics, second generation - schizophrenia, mania, bipolar disorder, major depression',
    'Quinagolide' : 'dopamine receptor agonists - hyperprolactinaemia',
    'Quinapril' : 'ACEi - hypertension, heart failure',
    'Quinine' : 'antimalarials - malaria, nocturnal leg cramps',
    'Raltegravir' : 'antiretroviral - HIV infection',
    'Raltitrexed' : 'antineoplastics, other - palliation of colorectal cancer',
    'Ramipril' : 'ACEi - hypertension, heart failure, diabetic nephropathy',
    'Ramucirumab' : 'chemotherapy - monoclonal antibodies - gastric or GOJ adenocarcinoma, metastatic colorectal cancer, metastatic non-small cell lung cancer',
    'Ranibizumab' : 'VEGF inhibitors - neovascular (wet) AMD, macular oedema, choroidal neovascularisation',
    'Ranitidine' : 'H2 receptor antagonists - gastroduodenal ulceration, reflux oesophagitis, gastric acid reduction, prophylaxis of peptic ulcers',
    'Ranolazine' : '?? - stable angina',
    'Rasagiline' : 'MAO inhibitors - Parkinsons disease',
    'Rasburicase' : 'uric acid sequestrant - acute hyperuricaemia before initiation of chemotherapy in patients at risk of tumour lysis syndrome',
    'Ravulizumab' : 'DMARD - monoclonal antibody - paroxysmal nocturnal haemoglobinuria, atypical haemolytic uraemic syndrome',
    'Reboxetine' : 'antidepressants, other - major depression',
    'Regorafenib' : 'chemotherapy - protein kinase inhibitor - colorectal cancer, hepatocellular carcinomma',
    'Remdesivir' : 'antivirals - other - covid 19',
    'Remifentanil' : 'opioids - analgesia and anaesthesia',
    'Remimazolam' : 'benzodiazepines - sedation',
    'Repaglinide' : 'insulin secretalogues - T2DM',
    'Reslizumab' : 'DMARD - monoclonal antibody - severe eosinophilic asthma',
    'Ribavirin' : 'antivirals - nucleoside analogues - bronchiolitis, RSV, parainfluenza, adenovirus infection in immunocompromised children',
    'Ribociclib' : 'chemotherapy - protein kinase inhibitor - metastatic breast cancer',
    'Rifampicin' : 'rifamycin antibiotics - brucellosis, legionnaires disease, severe staphylococcal infections, endocarditis, TB, Hib prevention, meningococcal meningitis prevention, leprosy',
    'Rilpivirine' : 'antiretroviral - HIV infection',
    'Riluzole' : 'neuroprotective drugs - amyotrophic lateral sclerosis (ALS)',
    'Rimegepant' : 'DMARD - monoclonal antibody - acute migraine, migraine prophylaxis',
    'Riociguat' : 'guanylate cyclase agonist - pulmonary hypertension',
    'Ripretinib' : 'chemotherapy - protein kinase inhibitor - gastrointestinal stromal tumour',
    'Risankizumab' : 'DMARD - interleukin inhibitors - plaque psoriasis, psoriatic arthritis',
    'Risdiplam' : 'drugs for neuromuscular disorders - 5q spinal muscular atrophy',
    'Risperidone' : 'antipsychotics, second generation - schizophrenia, psychosis, mania, aggression in alzheimers',
    'Ritonavir' : 'antiretroviral - HIV infection',
    'Rituximab' : 'anti-lymphocyte monoclonal antibodies - RA, non-hodgkins lymphoma, CLL, granulomatosis with palyangiitis and microscopic polyangiitis, phemigus vulgaris',
    'Rivaroxaban' : 'direct factor Xa inhibitor - prophylaxis of VTE, treatment of DVT/PE, prophylaxis of stroke in AF',
    'Rivastigmine' : 'acetylcholinesterase inhibitor - Alzheimers disease, Parkinsons disease',
    'Rizatriptan' : 'triptans - acute migraine',
    'Rocuronium' : 'non-depolarising neuromuscular blockers - neuromuscular blockade during surgery and intubation',
    'Roflumilast' : 'PDE4 inhibitor - COPD',
    'Romiplostim' : 'thrombopoietin receptor agonist - chronic immune thrombocytopenic purpura',
    'Romosozumab' : 'DMARD - monoclonal antibody - osteoporosis',
    'Ropinirole' : 'dopamine receptor agonists - Parkinsons disease, restless legs syndrome',
    'Rosuvastatin' : 'HMG-CoA reductase inhibitor - hyperlipidaemia, homozygous familial hypercholesterolaemia, secondary prevenetion of cardiovascular events',
    'Rotigotine' : 'dopamine receptor agonists - Parkinsons disease, restless legs syndrome',
    'Roxadustat' : '?? - anaemia in CKD',
    'Rucaparib' : 'antineoplastics, other - ovarian cancer, peritoneal cancer',
    'Rufinamide' : 'antiepileptics - seizures in lennox-gastaut syndrome',
    'Rupatadine' : 'non-sedating antihistamine - allergic reactions',
    'Ruxolitinib' : 'chemotherapy - protein kinase inhibitor - splenomegaly',
    'Safinamide' : 'MAO inhibitors - Parkinsons disease',
    'Salbutamol' : 'short acting beta agonists - asthma, premature labour, bronchospasm',
    'Salmeterol' : 'long acting beta agonists - asthma, COPD, bronchospasm',
    'Sarilumab' : 'DMARD - interleukin inhibitors - RA',
    'Saxagliptin' : 'DPP4 inhibitors - T2DM',
    'Secukinumab' : 'DMARD - interleukin inhibitors - AS, psoriatic arthritis, plaque psoriasis',
    'Selenium' : 'vitamins and analogues - selenium deficiency, seborrhoeic dermatitis, pityriasis, versicolor',
    'Selexipag' : 'antiplatelet drugs - pulmonary hypertension',
    'Semaglutide' : 'GLP1 receptor agonist - T2DM',
    'Senna' : 'stimulant laxatives - constipation',
    'Sertraline' : 'SSRIs - depression, panic disorder, OCD, PTSD',
    'Setmelanotide' : 'antiobesity drugs - obesity with genetic aetiology',
    'Sevelamer' : 'phosphate binders - hyperphosphataemia',
    'Sevoflurane' : 'volatile liquid anaesthetics - anaesthesia',
    'Sildenafil' : 'PDE5 inhibitors - erectile dysfunction, pulmonary hypertension, digital ulcers in systemic sclerosis',
    'Simeticone' : 'antifoaming agents - colic',
    'Simvastatin' : 'HMG-CoA reductase inhibitor - hyperlipidaemia, homozygous familial hypercholesterolaemia, secondary prevenetion of cardiovascular events',
    'Siponimod' : 'Immunomodulating drugs - MS',
    'Sirolimus' : 'calcineurin inhibitors - transplant rejection',
    'Sitagliptin' : 'DPP4 inhibitors - T2DM',
    'Sofosbuvir' : 'antivirals - nucleotide analogues - chronic hepatitis C',
    'solifenacin' : 'antimuscarinics - urinary frequency, urgency and incontinence',
    'Solriamfetol' : 'sympathomimetics - excessive sleepiness in narcolepsy',
    'Somatropin' : 'hormones and analogues - Turner syndrome, growth hormone deficiency',
    'Sorafenib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, thyroid cancer, hepatocellular carcinoma',
    'sotalol' : 'beta blocker - ventricular tachyarrhythmias, paroxysmal atrial arrhythmias, maintenance of sinus rhythm',
    'Sotorasib' : 'antineoplastics, other - non-small cell lung cancer with KRAS mutation',
    'Sotrovimab' : 'monoclonal antibodies - covid 19',
    'Spironolactone' : 'mineralocorticoid receptor antagonists - oedema, ascites, nephrotic syndrome, heart failure, hypertension',
    'Sterculia' : 'bulk forming laxative - constipation',
    'Stiripentol' : 'antiepileptics - tonic-clonic seizures in Dravet syndrome',
    'Streptokinase' : 'fibrinolytics (plasminogen activators) - MI, PE/DVT, central retinal venous or arterial thrombosis',
    'Streptomycin' : 'aminoglycoside antibiotics - TB, enterococcal endocarditis',
    'Streptozocin' : 'chemotherapy - alkylating agents - neuroendocrine tumours',
    'Sucralfate' : 'metal salts - peptic ulceration, chronic gastritis, prophylaxis of stress ulceration',
    'Sugammadex' : 'antidotes - reveral of neuromuscular blockade',
    'Sulfadiazine' : 'sulphonamide antibiotic - prevention of rheumatic fever recurrence',
    'Sulfasalazine' : 'aminosalicylates - active crohns disease, active ulverative colitis, active RA, maintenance of UC remission',
    'Sulindac' : 'NSAID - pain and inflammation in rheumatoid conditions, acute gout',
    'Sulpiride' : 'antipsychotics, first generation - schizophrenia',
    'Sumatriptan' : 'triptans - acute migraine, cluster headache',
    'Sunitinib' : 'chemotherapy - protein kinase inhibitor - gastrointestinal stromal tumours, pancreatic neuroendocrine tumours',
    'Suxamethonium' : 'depolarising neuromuscular blockers - neuromuscular blockade during surgery and intubation',
    'Tacalcitol' : 'vitamins and analogues - plaque psoriasis',
    'Tacrolimus' : 'calcineurin inhibitors - atopic eczema, psoriasis, transplant rejection',
    'Tadalafil' : 'PDE5 inhibitors - erectile dysfunction, pulmonary hypertension',
    'Tafamidis' : 'neuroprotective drugs - transthyretin amyloidosis',
    'Tafasitamab' : 'chemotherapy - monoclonal antibodies - diffuse large B cell lymphoma',
    'Tafluprost' : 'prostaglandins and analogues - ocular hypertension, chronic glaucoma',
    'Talazoparib' : 'antineoplastics, other - breast cancer',
    'Tamoxifen' : 'anti-oestrogens - oestrogen receptor positive breast cancer, anovulatory infertility, gynaecomastia',
    'Tamsulosin' : 'alpha-adrenoreceptor blockers - BPH',
    'Tapentadol' : 'opioids - pain',
    'Tazarotene' : 'retinoids - plaque psoriasis',
    'Tebentafusp' : 'antineoplastics, other - uveal melanoma',
    'Tedizolid' : 'oxazolidinone antibiotic - acute skin and skin structure infections',
    'Teduglutide' : 'amino acids and derivatives - short bowel syndrome',
    'Teicoplanin' : 'glycopeptide antibiotics - C diff, foot infections, cellulitis, complicated infections, pneumonia, endocarditis, meningitis, bacteraemia, surgical prophylaxis',
    'Telmisartan' : 'ARB - hypertension, prevention of cardiovascular events',
    'Temazepam' : 'benzodiazepines - insomnia, sedation',
    'Temocillin' : 'penicillin antibiotics - septicaemia, UTI, LRTI caused by gram negative bacteria',
    'Temozolomide' : 'chemotherapy - alkylating agents - gioblastoma multiforme',
    'Temsirolimus' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma, mantle cell lymphoma',
    'Tenecteplase' : 'fibrinolytics (plasminogen activators) - acute MI',
    'Tenoxicam' : 'NSAID - pain and inflammation in rheumatoid conditions',
    'Terazosin' : 'alpha-adrenoreceptor blockers - hypertension, BPH',
    'Terbinafine' : 'antifungals - tinea infections, pityriasis versicolor, cutaneous candidiasis',
    'Terbutaline' : 'short acting beta agonists - asthma, premature labour',
    'Teriflunomide' : 'Immunomodulating drugs - MS',
    'Teriparatide' : 'parathyroid hormones and analogues - osteoporosis',
    'Terlipressin' : 'ADH analogues - oesophageal variceal bleeding',
    'Testosterone' : 'hormones and analogues - low libido in postmenopausal women, hypogonadism due to androgen deficiency',
    'Tetrabenazine' : 'VMAT2 inhibitors - movement disorders, tardive dyskinesia',
    'Tetracaine' : 'local anaesthetics - local anaesthesia of eye or before cannulation',
    'Tetracycline' : 'tetracyclines - acne vulgaris, rosacea, non-gonococcal urethritis, H pylori, chlamydia, rickettsia, mycoplasma',
    'Thalidomide' : 'chemotherapy - thalidomides - multiple myeloma',
    'Thiopental' : 'barbituates - status epilepticus, anaesthesia',
    'Thiamine' : 'vitamins and analogues - thiamine deficiency',
    'Theophylline' : 'xanthines - asthma',
    'thyrotropin' : 'hormones and analogues - detection of thyroid remnants and cancer post thyroidectomy',
    'Tiagabine' : 'antiepileptics - focal seizures',
    'Tibolone' : 'oestrogens - osteoporosis prophylaxis',
    'Ticagrelor' : 'antiplatelet drugs - prevention of atherothrombotic events',
    'Tigecycline' : 'tetracyclines - complicated skin, soft tissue and intra-abdominal infections',
    'Tildrakizumab' : 'DMARD - interleukin inhibitors - plaque psoriasis',
    'timolol' : 'beta blocker - hypertension, angina, migraine prophylaxis, ocular hypertension, glaucoma',
    'Tioconazole' : 'antifungals - fungal nail infection',
    'Tioguanine' : 'chemotherapy - antimetabolites - leukaemias',
    'Tiotropium' : 'antimuscarinics - COPD',
    'Tipranavir' : 'antiretroviral - HIV infection',
    'Tirbanibulin' : 'chemotherapy - protein kinase inhibitor - actinic keratosis',
    'Tirofiban' : 'antiplatelet drugs - NSTEMI, STEMI, unstable angina',
    'Tivozanib' : 'chemotherapy - protein kinase inhibitor - renal cell carcinoma',
    'Tizanidine' : 'muscle relaxants - muscle spasm',
    'Tobramycin' : 'aminoglycoside antibiotics - severe infections, septicaemia, meningitis, pneumonia, UTI',
    'Tocilizumab' : 'DMARD - interleukin inhibitors - RA, giant cell arteritis, covid 19',
    'Tofacitinib' : 'DMARD - JAK1 inhibitor - RA, psoriatic arthritis, ulcerative colitis, AS',
    'Tolbutamide' : 'sulfonylureas - T2DM',
    'Tolcapone' : 'catechol-o-methyltransferase inhibitors - Parkinsons disease',
    'Tolvaptan' : 'vasopressin receptor antagonist - autosomal dominant polycystic kidney disease, hyponatraemia secondary to SIADH',
    'Topiramate' : 'antiepileptics - tonic-clonic seizures, focal seizures, seizures in lennox-gastaut syndrome, migraine prophylaxis',
    'Topotecan' : 'chemotherapy - topoisomerase inhibitors - metastatic ovarian cancer, cervical cancer, small-cell lung cancer',
    'Torasemide' : 'loop diuretic - oedema, hypertension',
    'Toremifene' : 'anti-oestrogens - oestrogen receptor positive breast cancer',
    'Trabectedin' : 'chemotherapy - plant alkaloids - soft tissue sarcoma, ovarian cancer',
    'Tralokinumab' : 'DMARD - interleukin inhibitors - atopic eczema',
    'tramadol' : 'opioids - pain',
    'Trametinib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma',
    'Trandolapril' : 'ACEi - hypertension',
    'Trastuzumab' : 'chemotherapy - monoclonal antibodies - breast cancer (HER2 +ve)',
    'Trazodone' : 'antidepressants, other - depression, anxiety',
    'Travoprost' : 'prostaglandins and analogues - ocular hypertension, chronic glaucoma',
    'Treosulfan' : 'chemotherapy - alkylating agents - ovarian cancer',
    'Treprostinil' : 'prostaglandins and analogues - pulmonary hypertension',
    'Tretinoin' : 'retinoids - acute promyelocytic leukaemia',
    'Triamterene' : 'potassium sparing diuretics - oedema, potassium conservation with thiazide and loop diuretics',
    'Trientine' : 'antidotes and chelating agents - wilsons disease',
    'Trifarotene' : 'retinoids - acne vulgaris',
    'Trimethoprim' : 'antibiotics, other - RTI, UTI, PJP, acne vulgaris, shigellosis, diverticulitis',
    'Trimipramine' : 'tricyclic antidepressants - depression',
    'Triptorelin' : 'gonadotrophin releasing hormones - endometriosis, prostate cancer',
    'Tropicamide' : 'antimuscarinics - fundoscopy',
    'Tryptophan' : 'antidepressants, other - depression',
    'Tucatinib' : 'chemotherapy - protein kinase inhibitor - breast cancer (HER2 +ve)',
    'Ulipristal' : 'progesterone receptor modulators - emergency contraception, uterine fibroids',
    'Umeclidinium' : 'antimuscarinics - COPD',
    'Upadacitinib' : 'DMARD - JAK1 inhibitor - RA, psoriatic arthritis, atopic eczema, AS',
    'Urofollitropin' : 'gonadotrophins - infertility',
    'Urokinase' : 'fibrinolytics (plasminogen activators) - DVT, PE, occlussive PAD',
    'Ustekinumab' : 'DMARD - interleukin inhibitors - IBD, psoriatic arthritis, plaque psoriasis',
    'Valaciclovir' : 'antivirals - nucleoside analogues - HSV, HZV, VZV infection',
    'Valganciclovir' : 'antivirals - nucleoside analogues - CMV retinitis, prevention of CMV post-transplant',
    'Valsartan' : 'ARB - hypertension, heart failure',
    'Vancomycin' : 'glycopeptide antibiotics - C diff, foot infections, cellulitis, complicated infections, pneumonia, endocarditis, meningitis, bacteraemia, surgical prophylaxis',
    'Vandetanib' : 'chemotherapy - protein kinase inhibitor - medullary thryroid cancer',
    'verapamil' : 'calcium channel blockers - supraventricular arrhythmias, tachyarrhythmias, angina, hypertension, prophylaxis of cluster headache',
    'Vecuronium' : 'non-depolarising neuromuscular blockers - surgical paralysis',
    'Vardenafil' : 'PDE5 inhibitors - erectile dysfunction',
    'Varenicline' : 'Nicotine receptor agonist - smoking cessation',
    'Vasopressin' : 'ADH analogues - pituitary diabetes insipidus, oesophageal variceal bleeding',
    'Vedolizumab' : 'anti-lymphocyte monoclonal antibodies - crohns disease, ulcerative colitis',
    'Vemurafenib' : 'chemotherapy - protein kinase inhibitor - metastatic melanoma',
    'Venetoclax' : 'antineoplastics, other - CLL, AML',
    'Venlafaxine' : 'SNRI - depression, generalised anxiety disorder, social anxiety disorder, panic disorder',
    'Vigabatrin' : 'antiepileptics - focal seizures',
    'Vildagliptin' : 'DPP4 inhibitors - T2DM',
    'Vincristine' : 'chemotherapy - vinca alkaloids - leukaemias, lymphomas, breast cancer, lung cancer',
    'Vinorelbine' : 'chemotherapy - vinca alkaloids - breast cancer, non-small cell lung cancer',
    'Vismodegib' : 'antineoplastics, other - metastatic basal cell carcinoma',
    'Voriconazole' : 'antifungals - invasive asperigillosis, invasive candidiasis',
    'Vortioxetine' : 'serotonin reuptake inhibitor, partial serotonin agonists - major depression',
    'Voxelotor' : 'HbS polymerisation inhibitors - sickle cell disease',
    'Warfarin' : 'vitamin K antagonists - prophylaxis of embolisation in AF, prosthetic heart valves',
    'Xipamide' : 'thiazide like diuretics - oedema, hypertension',
    'Zanamivir' : 'antivirals - neuraminidase inhibitors - influenza',
    'Zanubrutinib' : 'chemotherapy - protein kinase inhibitor - Waldenstroms macroglobinaemia',
    'Zidovudine' : 'antiretroviral - HIV infection',
    'Zolmitriptan' : 'triptans - acute migraine, cluster headache',
    'Zonisamide' : 'antiepileptics - focal seizures',
    'Zopiclone' : 'non-benzodiazepine sedatives and hypnotics - insomnia',
    'Zuclopenthixol' : 'antipsychotics, first generation - schizophrenia'
}